import {
  type Recommendation,
  type EngineUser,
  type EngineContext,
  type TrendingPlace,
  type TrendingEvent,
  type TrendingBusiness,
  type TrendingPerson,
  type TrendingDriver,
  ActivityLevel,
  RecommendationType,
  ContextPeriod,
  ContextDay,
  ContextLocation,
} from "./engine-types";

const NOW = new Date().toISOString();
const HOUR_AGO = new Date(Date.now() - 60 * 60 * 1000).toISOString();
const TWO_HOURS_AGO = new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString();
const YESTERDAY = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
const TOMORROW = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString();
const NEXT_WEEK = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString();
const IN_TWO_DAYS = new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString();

export const mockUser: EngineUser = {
  id: "user-001",
  name: "Lucas Martins",
  handle: "lucas.m",
  photoUrl: "https://i.pravatar.cc/150?img=33",
  interests: ["Musica", "Gastronomia", "Tecnologia", "Arte", "Vida noturna", "Fitness"],
  favoritePlaceIds: ["place-001", "place-003", "place-007"],
  vibeTags: ["Criativo", "Aventureiro", "Sociavel"],
  location: { lat: -23.5505, lng: -46.6333, label: "Av. Paulista, Sao Paulo" },
  context: {
    period: ContextPeriod.NOITE,
    day: ContextDay.FIM_DE_SEMANA,
    location: ContextLocation.CENTRO,
    lat: -23.5505,
    lng: -46.6333,
    timestamp: NOW,
  },
};

export const mockContext: EngineContext = {
  period: ContextPeriod.NOITE,
  day: ContextDay.FIM_DE_SEMANA,
  location: ContextLocation.CENTRO,
  lat: -23.5505,
  lng: -46.6333,
  timestamp: NOW,
};

const MOCK_PEOPLE: Recommendation[] = [
  {
    id: "person-001",
    type: RecommendationType.PERSON,
    score: {
      interest: 90,
      distance: 80,
      popularity: 70,
      compatibility: 85,
      time: 90,
      recency: 80,
      total: 84,
    },
    reasons: ["COMPATIBILIDADE", "INTERESSE"],
    title: "Giulia Santos",
    subtitle: "Designer UX",
    imageUrl: "https://i.pravatar.cc/150?img=23",
    distanceMeters: 350,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: true,
    metadata: {
      kind: "person",
      age: 28,
      profession: "Designer UX",
      compatibilityPercent: 92,
      mutualConnections: 5,
      isOnline: true,
      lastSeen: NOW,
    },
  },
  {
    id: "person-002",
    type: RecommendationType.PERSON,
    score: {
      interest: 85,
      distance: 90,
      popularity: 60,
      compatibility: 80,
      time: 85,
      recency: 70,
      total: 80,
    },
    reasons: ["DISTANCIA", "COMPATIBILIDADE"],
    title: "Rafael Costa",
    subtitle: "Desenvolvedor",
    imageUrl: "https://i.pravatar.cc/150?img=12",
    distanceMeters: 120,
    activityLevel: ActivityLevel.BOMBANDO,
    trending: false,
    metadata: {
      kind: "person",
      age: 31,
      profession: "Desenvolvedor",
      compatibilityPercent: 87,
      mutualConnections: 3,
      isOnline: true,
      lastSeen: NOW,
    },
  },
  {
    id: "person-003",
    type: RecommendationType.PERSON,
    score: {
      interest: 80,
      distance: 70,
      popularity: 75,
      compatibility: 78,
      time: 80,
      recency: 65,
      total: 75,
    },
    reasons: ["INTERESSE", "POPULARIDADE"],
    title: "Ana Beatriz",
    subtitle: "Fotografa",
    imageUrl: "https://i.pravatar.cc/150?img=47",
    distanceMeters: 680,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "person",
      age: 25,
      profession: "Fotografa",
      compatibilityPercent: 78,
      mutualConnections: 2,
      isOnline: false,
      lastSeen: HOUR_AGO,
    },
  },
  {
    id: "person-004",
    type: RecommendationType.PERSON,
    score: {
      interest: 75,
      distance: 85,
      popularity: 65,
      compatibility: 75,
      time: 70,
      recency: 60,
      total: 73,
    },
    reasons: ["DISTANCIA", "INTERESSE"],
    title: "Pedro Henrique",
    subtitle: "Chef de Cozinha",
    imageUrl: "https://i.pravatar.cc/150?img=15",
    distanceMeters: 450,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "person",
      age: 34,
      profession: "Chef de Cozinha",
      compatibilityPercent: 75,
      mutualConnections: 1,
      isOnline: true,
      lastSeen: NOW,
    },
  },
  {
    id: "person-005",
    type: RecommendationType.PERSON,
    score: {
      interest: 70,
      distance: 60,
      popularity: 80,
      compatibility: 72,
      time: 75,
      recency: 70,
      total: 71,
    },
    reasons: ["POPULARIDADE", "COMPATIBILIDADE"],
    title: "Camila Ferreira",
    subtitle: "DJ & Produtora",
    imageUrl: "https://i.pravatar.cc/150?img=26",
    distanceMeters: 900,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: true,
    metadata: {
      kind: "person",
      age: 27,
      profession: "DJ & Produtora",
      compatibilityPercent: 72,
      mutualConnections: 8,
      isOnline: true,
      lastSeen: NOW,
    },
  },
  {
    id: "person-006",
    type: RecommendationType.PERSON,
    score: {
      interest: 65,
      distance: 55,
      popularity: 60,
      compatibility: 68,
      time: 65,
      recency: 55,
      total: 63,
    },
    reasons: ["INTERESSE", "HORARIO"],
    title: "Thiago Almeida",
    subtitle: "Arquiteto",
    imageUrl: "https://i.pravatar.cc/150?img=18",
    distanceMeters: 1200,
    activityLevel: ActivityLevel.CALMO,
    trending: false,
    metadata: {
      kind: "person",
      age: 30,
      profession: "Arquiteto",
      compatibilityPercent: 68,
      mutualConnections: 0,
      isOnline: false,
      lastSeen: TWO_HOURS_AGO,
    },
  },
  {
    id: "person-007",
    type: RecommendationType.PERSON,
    score: {
      interest: 82,
      distance: 75,
      popularity: 70,
      compatibility: 82,
      time: 80,
      recency: 75,
      total: 78,
    },
    reasons: ["COMPATIBILIDADE", "DISTANCIA"],
    title: "Mariana Lopes",
    subtitle: "Musicista",
    imageUrl: "https://i.pravatar.cc/150?img=45",
    distanceMeters: 280,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: false,
    metadata: {
      kind: "person",
      age: 26,
      profession: "Musicista",
      compatibilityPercent: 82,
      mutualConnections: 4,
      isOnline: true,
      lastSeen: NOW,
    },
  },
  {
    id: "person-008",
    type: RecommendationType.PERSON,
    score: {
      interest: 60,
      distance: 95,
      popularity: 55,
      compatibility: 65,
      time: 60,
      recency: 50,
      total: 62,
    },
    reasons: ["DISTANCIA"],
    title: "Felipe Rocha",
    subtitle: "Personal Trainer",
    imageUrl: "https://i.pravatar.cc/150?img=53",
    distanceMeters: 80,
    activityLevel: ActivityLevel.BOMBANDO,
    trending: false,
    metadata: {
      kind: "person",
      age: 29,
      profession: "Personal Trainer",
      compatibilityPercent: 65,
      mutualConnections: 1,
      isOnline: true,
      lastSeen: NOW,
    },
  },
  {
    id: "person-009",
    type: RecommendationType.PERSON,
    score: {
      interest: 72,
      distance: 68,
      popularity: 78,
      compatibility: 70,
      time: 72,
      recency: 68,
      total: 71,
    },
    reasons: ["POPULARIDADE", "INTERESSE"],
    title: "Isabela Mendes",
    subtitle: "Influenciadora Digital",
    imageUrl: "https://i.pravatar.cc/150?img=32",
    distanceMeters: 520,
    activityLevel: ActivityLevel.BOMBANDO,
    trending: true,
    metadata: {
      kind: "person",
      age: 24,
      profession: "Influenciadora Digital",
      compatibilityPercent: 70,
      mutualConnections: 12,
      isOnline: true,
      lastSeen: NOW,
    },
  },
  {
    id: "person-010",
    type: RecommendationType.PERSON,
    score: {
      interest: 55,
      distance: 72,
      popularity: 50,
      compatibility: 60,
      time: 55,
      recency: 45,
      total: 56,
    },
    reasons: ["INTERESSE", "LOCAL"],
    title: "Bruno Nascimento",
    subtitle: "Estudante Medicina",
    imageUrl: "https://i.pravatar.cc/150?img=59",
    distanceMeters: 750,
    activityLevel: ActivityLevel.CALMO,
    trending: false,
    metadata: {
      kind: "person",
      age: 22,
      profession: "Estudante de Medicina",
      compatibilityPercent: 60,
      mutualConnections: 0,
      isOnline: false,
      lastSeen: YESTERDAY,
    },
  },
];

const MOCK_EVENTS: Recommendation[] = [
  {
    id: "event-001",
    type: RecommendationType.EVENT,
    score: {
      interest: 95,
      distance: 85,
      popularity: 90,
      compatibility: 80,
      time: 95,
      recency: 90,
      total: 89,
    },
    reasons: ["EVENTO", "TENDENCIA", "POPULARIDADE"],
    title: "Sunset no Ibirapuera",
    subtitle: "Musica ao vivo",
    imageUrl: "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=400",
    distanceMeters: 450,
    activityLevel: ActivityLevel.BOMBANDO,
    trending: true,
    metadata: {
      kind: "event",
      date: NOW,
      location: "Parque Ibirapuera",
      interestedCount: 234,
      attendingCount: 156,
      isInterested: true,
      isAttending: false,
      category: "Musica",
    },
  },
  {
    id: "event-002",
    type: RecommendationType.EVENT,
    score: {
      interest: 88,
      distance: 70,
      popularity: 85,
      compatibility: 85,
      time: 80,
      recency: 85,
      total: 82,
    },
    reasons: ["COMPATIBILIDADE", "EVENTO"],
    title: "Tech Meetup SP",
    subtitle: "Networking tech",
    imageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400",
    distanceMeters: 1200,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: true,
    metadata: {
      kind: "event",
      date: TOMORROW,
      location: "WeWork Faria Lima",
      interestedCount: 89,
      attendingCount: 67,
      isInterested: true,
      isAttending: true,
      category: "Tecnologia",
    },
  },
  {
    id: "event-003",
    type: RecommendationType.EVENT,
    score: {
      interest: 82,
      distance: 60,
      popularity: 78,
      compatibility: 75,
      time: 75,
      recency: 80,
      total: 76,
    },
    reasons: ["LOCAL", "EVENTO"],
    title: "Feira Gastronomica",
    subtitle: "Comida e bebida",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
    distanceMeters: 800,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: false,
    metadata: {
      kind: "event",
      date: IN_TWO_DAYS,
      location: "Praca da Republica",
      interestedCount: 312,
      attendingCount: 198,
      isInterested: false,
      isAttending: false,
      category: "Gastronomia",
    },
  },
  {
    id: "event-004",
    type: RecommendationType.EVENT,
    score: {
      interest: 78,
      distance: 90,
      popularity: 70,
      compatibility: 72,
      time: 70,
      recency: 75,
      total: 74,
    },
    reasons: ["DISTANCIA", "EVENTO"],
    title: "Yoga ao Ar Livre",
    subtitle: "Bem-estar",
    imageUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400",
    distanceMeters: 200,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "event",
      date: NEXT_WEEK,
      location: "Parque Villa-Lobos",
      interestedCount: 45,
      attendingCount: 32,
      isInterested: false,
      isAttending: false,
      category: "Fitness",
    },
  },
  {
    id: "event-005",
    type: RecommendationType.EVENT,
    score: {
      interest: 85,
      distance: 55,
      popularity: 92,
      compatibility: 78,
      time: 85,
      recency: 88,
      total: 81,
    },
    reasons: ["POPULARIDADE", "TENDENCIA"],
    title: "Festival Eletronico",
    subtitle: "3 dias de musica",
    imageUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400",
    distanceMeters: 2500,
    activityLevel: ActivityLevel.MUITO_CHEIO,
    trending: true,
    metadata: {
      kind: "event",
      date: NEXT_WEEK,
      location: "Autodromo de Interlagos",
      interestedCount: 1250,
      attendingCount: 890,
      isInterested: true,
      isAttending: false,
      category: "Musica",
    },
  },
  {
    id: "event-006",
    type: RecommendationType.EVENT,
    score: {
      interest: 70,
      distance: 80,
      popularity: 65,
      compatibility: 68,
      time: 65,
      recency: 70,
      total: 70,
    },
    reasons: ["INTERESSE", "LOCAL"],
    title: "Workshop Fotografia",
    subtitle: "Aprenda tecnica",
    imageUrl: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=400",
    distanceMeters: 650,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "event",
      date: IN_TWO_DAYS,
      location: "CCBB Sao Paulo",
      interestedCount: 28,
      attendingCount: 20,
      isInterested: false,
      isAttending: false,
      category: "Arte",
    },
  },
  {
    id: "event-007",
    type: RecommendationType.EVENT,
    score: {
      interest: 65,
      distance: 75,
      popularity: 60,
      compatibility: 65,
      time: 60,
      recency: 65,
      total: 65,
    },
    reasons: ["COMPATIBILIDADE", "HORARIO"],
    title: "Roda de Samba",
    subtitle: "Samba & Pagode",
    imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400",
    distanceMeters: 900,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: false,
    metadata: {
      kind: "event",
      date: NOW,
      location: "Bar do Mane",
      interestedCount: 67,
      attendingCount: 45,
      isInterested: false,
      isAttending: false,
      category: "Musica",
    },
  },
  {
    id: "event-008",
    type: RecommendationType.EVENT,
    score: {
      interest: 60,
      distance: 50,
      popularity: 55,
      compatibility: 60,
      time: 55,
      recency: 60,
      total: 57,
    },
    reasons: ["DISTANCIA", "LOCAL"],
    title: "Exposicao Arte",
    subtitle: "Galeria cultural",
    imageUrl: "https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?w=400",
    distanceMeters: 350,
    activityLevel: ActivityLevel.CALMO,
    trending: false,
    metadata: {
      kind: "event",
      date: NEXT_WEEK,
      location: "Pinacoteca",
      interestedCount: 156,
      attendingCount: 89,
      isInterested: false,
      isAttending: false,
      category: "Arte",
    },
  },
  {
    id: "event-009",
    type: RecommendationType.EVENT,
    score: {
      interest: 72,
      distance: 65,
      popularity: 75,
      compatibility: 70,
      time: 70,
      recency: 72,
      total: 70,
    },
    reasons: ["POPULARIDADE", "EVENTO"],
    title: "Corrida de Rua 5K",
    subtitle: "Corrida solidaria",
    imageUrl: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=400",
    distanceMeters: 1500,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: false,
    metadata: {
      kind: "event",
      date: NEXT_WEEK,
      location: "Marginal Pinheiros",
      interestedCount: 234,
      attendingCount: 178,
      isInterested: false,
      isAttending: false,
      category: "Esporte",
    },
  },
  {
    id: "event-010",
    type: RecommendationType.EVENT,
    score: {
      interest: 68,
      distance: 82,
      popularity: 62,
      compatibility: 66,
      time: 62,
      recency: 68,
      total: 66,
    },
    reasons: ["HORARIO", "INTERESSE"],
    title: "Cinema ao Ar Livre",
    subtitle: "Filme classico",
    imageUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400",
    distanceMeters: 500,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "event",
      date: NOW,
      location: "Praca Charles Miller",
      interestedCount: 89,
      attendingCount: 56,
      isInterested: false,
      isAttending: false,
      category: "Cinema",
    },
  },
];

const MOCK_BUSINESSES: Recommendation[] = [
  {
    id: "biz-001",
    type: RecommendationType.BUSINESS,
    score: {
      interest: 88,
      distance: 90,
      popularity: 85,
      compatibility: 80,
      time: 85,
      recency: 80,
      total: 85,
    },
    reasons: ["DISTANCIA", "POPULARIDADE"],
    title: "Cafe Central",
    subtitle: "Cafes artesanais",
    imageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=400",
    distanceMeters: 150,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: true,
    metadata: {
      kind: "business",
      category: "Cafe",
      rating: 4.7,
      reviewCount: 234,
      priceRange: "$$",
      isFollowing: true,
      offerCount: 2,
    },
  },
  {
    id: "biz-002",
    type: RecommendationType.OFFER,
    score: {
      interest: 82,
      distance: 75,
      popularity: 80,
      compatibility: 75,
      time: 90,
      recency: 85,
      total: 81,
    },
    reasons: ["HORARIO", "POPULARIDADE"],
    title: "Burger House",
    subtitle: "Combo Duplo 30% OFF",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400",
    distanceMeters: 300,
    activityLevel: ActivityLevel.BOMBANDO,
    trending: true,
    metadata: {
      kind: "offer",
      businessName: "Burger House",
      businessLogo: "",
      discountPercent: 30,
      validUntil: "31 Jul",
      originalPrice: 59.9,
      finalPrice: 41.93,
    },
  },
  {
    id: "biz-003",
    type: RecommendationType.BUSINESS,
    score: {
      interest: 78,
      distance: 65,
      popularity: 72,
      compatibility: 78,
      time: 70,
      recency: 75,
      total: 74,
    },
    reasons: ["COMPATIBILIDADE", "LOCAL"],
    title: "Vinil Store",
    subtitle: "Discos e Vinis",
    imageUrl: "https://images.unsplash.com/photo-1483412033650-1015ddeb83d1?w=400",
    distanceMeters: 800,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "business",
      category: "Loja",
      rating: 4.5,
      reviewCount: 156,
      priceRange: "$$$",
      isFollowing: false,
      offerCount: 0,
    },
  },
  {
    id: "biz-004",
    type: RecommendationType.BUSINESS,
    score: {
      interest: 75,
      distance: 85,
      popularity: 78,
      compatibility: 72,
      time: 75,
      recency: 70,
      total: 76,
    },
    reasons: ["DISTANCIA", "POPULARIDADE"],
    title: "Sushi Tanaka",
    subtitle: "Comida Japonesa",
    imageUrl: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400",
    distanceMeters: 180,
    activityLevel: ActivityLevel.BOMBANDO,
    trending: true,
    metadata: {
      kind: "business",
      category: "Restaurante",
      rating: 4.8,
      reviewCount: 312,
      priceRange: "$$$",
      isFollowing: false,
      offerCount: 1,
    },
  },
  {
    id: "biz-005",
    type: RecommendationType.OFFER,
    score: {
      interest: 70,
      distance: 70,
      popularity: 68,
      compatibility: 70,
      time: 85,
      recency: 80,
      total: 72,
    },
    reasons: ["HORARIO", "INTERESSE"],
    title: "Padaria Paulista",
    subtitle: "Pao de fermento 25% OFF",
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400",
    distanceMeters: 450,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: false,
    metadata: {
      kind: "offer",
      businessName: "Padaria Paulista",
      businessLogo: "",
      discountPercent: 25,
      validUntil: "28 Jul",
      originalPrice: 35.0,
      finalPrice: 26.25,
    },
  },
  {
    id: "biz-006",
    type: RecommendationType.BUSINESS,
    score: {
      interest: 72,
      distance: 60,
      popularity: 75,
      compatibility: 68,
      time: 65,
      recency: 72,
      total: 69,
    },
    reasons: ["POPULARIDADE", "LOCAL"],
    title: "CrossFit Arena",
    subtitle: "Academia Funcional",
    imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400",
    distanceMeters: 950,
    activityLevel: ActivityLevel.BOMBANDO,
    trending: false,
    metadata: {
      kind: "business",
      category: "Academia",
      rating: 4.6,
      reviewCount: 189,
      priceRange: "$$",
      isFollowing: false,
      offerCount: 3,
    },
  },
  {
    id: "biz-007",
    type: RecommendationType.BUSINESS,
    score: {
      interest: 65,
      distance: 80,
      popularity: 62,
      compatibility: 65,
      time: 60,
      recency: 65,
      total: 66,
    },
    reasons: ["COMPATIBILIDADE", "DISTANCIA"],
    title: "Studio Criativo",
    subtitle: "Coworking & Eventos",
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400",
    distanceMeters: 350,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "business",
      category: "Coworking",
      rating: 4.3,
      reviewCount: 87,
      priceRange: "$$$",
      isFollowing: true,
      offerCount: 1,
    },
  },
  {
    id: "biz-008",
    type: RecommendationType.OFFER,
    score: {
      interest: 60,
      distance: 55,
      popularity: 65,
      compatibility: 60,
      time: 75,
      recency: 70,
      total: 63,
    },
    reasons: ["HORARIO", "POPULARIDADE"],
    title: "Farmacia Saude",
    subtitle: "Vitaminas 40% OFF",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
    distanceMeters: 600,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "offer",
      businessName: "Farmacia Saude",
      businessLogo: "",
      discountPercent: 40,
      validUntil: "25 Jul",
      originalPrice: 89.9,
      finalPrice: 53.94,
    },
  },
  {
    id: "biz-009",
    type: RecommendationType.BUSINESS,
    score: {
      interest: 68,
      distance: 72,
      popularity: 70,
      compatibility: 66,
      time: 68,
      recency: 68,
      total: 68,
    },
    reasons: ["POPULARIDADE", "COMPATIBILIDADE"],
    title: "Bar do Ze",
    subtitle: "Boteco & Petiscos",
    imageUrl: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=400",
    distanceMeters: 700,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: false,
    metadata: {
      kind: "business",
      category: "Bar",
      rating: 4.4,
      reviewCount: 267,
      priceRange: "$",
      isFollowing: false,
      offerCount: 0,
    },
  },
  {
    id: "biz-010",
    type: RecommendationType.BUSINESS,
    score: {
      interest: 55,
      distance: 50,
      popularity: 58,
      compatibility: 55,
      time: 55,
      recency: 55,
      total: 55,
    },
    reasons: ["DISTANCIA", "LOCAL"],
    title: "Floricultura Verde",
    subtitle: "Plantas & Flores",
    imageUrl: "https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400",
    distanceMeters: 1050,
    activityLevel: ActivityLevel.CALMO,
    trending: false,
    metadata: {
      kind: "business",
      category: "Loja",
      rating: 4.2,
      reviewCount: 45,
      priceRange: "$$",
      isFollowing: false,
      offerCount: 0,
    },
  },
];

const MOCK_DRIVERS: Recommendation[] = [
  {
    id: "driver-001",
    type: RecommendationType.DRIVER,
    score: {
      interest: 50,
      distance: 95,
      popularity: 85,
      compatibility: 40,
      time: 95,
      recency: 80,
      total: 77,
    },
    reasons: ["DISTANCIA", "HORARIO"],
    title: "Marcos Silva",
    subtitle: "Toyota Corolla",
    imageUrl: "https://i.pravatar.cc/150?img=68",
    distanceMeters: 120,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: false,
    metadata: {
      kind: "driver",
      rating: 4.9,
      vehicle: "Toyota Corolla Prata",
      plate: "ABC-1234",
      etaMinutes: 3,
      isAvailable: true,
      totalTrips: 1250,
    },
  },
  {
    id: "driver-002",
    type: RecommendationType.DRIVER,
    score: {
      interest: 50,
      distance: 90,
      popularity: 80,
      compatibility: 40,
      time: 90,
      recency: 75,
      total: 75,
    },
    reasons: ["DISTANCIA"],
    title: "Joao Santos",
    subtitle: "Honda Civic",
    imageUrl: "https://i.pravatar.cc/150?img=52",
    distanceMeters: 250,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "driver",
      rating: 4.8,
      vehicle: "Honda Civic Preto",
      plate: "DEF-5678",
      etaMinutes: 5,
      isAvailable: true,
      totalTrips: 890,
    },
  },
  {
    id: "driver-003",
    type: RecommendationType.DRIVER,
    score: {
      interest: 50,
      distance: 85,
      popularity: 75,
      compatibility: 40,
      time: 85,
      recency: 70,
      total: 72,
    },
    reasons: ["DISTANCIA", "HORARIO"],
    title: "Carlos Mendes",
    subtitle: "Hyundai HB20",
    imageUrl: "https://i.pravatar.cc/150?img=57",
    distanceMeters: 380,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "driver",
      rating: 4.7,
      vehicle: "Hyundai HB20 Branco",
      plate: "GHI-9012",
      etaMinutes: 7,
      isAvailable: true,
      totalTrips: 560,
    },
  },
  {
    id: "driver-004",
    type: RecommendationType.DRIVER,
    score: {
      interest: 50,
      distance: 80,
      popularity: 70,
      compatibility: 40,
      time: 80,
      recency: 65,
      total: 69,
    },
    reasons: ["DISTANCIA"],
    title: "Roberto Alves",
    subtitle: "Chevrolet Onix",
    imageUrl: "https://i.pravatar.cc/150?img=60",
    distanceMeters: 500,
    activityLevel: ActivityLevel.CALMO,
    trending: false,
    metadata: {
      kind: "driver",
      rating: 4.6,
      vehicle: "Chevrolet Onix Vermelho",
      plate: "JKL-3456",
      etaMinutes: 9,
      isAvailable: true,
      totalTrips: 340,
    },
  },
  {
    id: "driver-005",
    type: RecommendationType.DRIVER,
    score: {
      interest: 50,
      distance: 75,
      popularity: 65,
      compatibility: 40,
      time: 75,
      recency: 60,
      total: 66,
    },
    reasons: ["HORARIO"],
    title: "Fernando Costa",
    subtitle: "Volkswagen Golf",
    imageUrl: "https://i.pravatar.cc/150?img=64",
    distanceMeters: 650,
    activityLevel: ActivityLevel.CALMO,
    trending: false,
    metadata: {
      kind: "driver",
      rating: 4.5,
      vehicle: "VW Golf Azul",
      plate: "MNO-7890",
      etaMinutes: 11,
      isAvailable: false,
      totalTrips: 210,
    },
  },
  {
    id: "driver-006",
    type: RecommendationType.DRIVER,
    score: {
      interest: 50,
      distance: 70,
      popularity: 60,
      compatibility: 40,
      time: 70,
      recency: 55,
      total: 63,
    },
    reasons: ["DISTANCIA", "HORARIO"],
    title: "Andre Oliveira",
    subtitle: "Fiat Argo",
    imageUrl: "https://i.pravatar.cc/150?img=71",
    distanceMeters: 780,
    activityLevel: ActivityLevel.CALMO,
    trending: false,
    metadata: {
      kind: "driver",
      rating: 4.4,
      vehicle: "Fiat Argo Cinza",
      plate: "PQR-1234",
      etaMinutes: 13,
      isAvailable: false,
      totalTrips: 180,
    },
  },
  {
    id: "driver-007",
    type: RecommendationType.DRIVER,
    score: {
      interest: 50,
      distance: 88,
      popularity: 78,
      compatibility: 40,
      time: 88,
      recency: 78,
      total: 76,
    },
    reasons: ["DISTANCIA", "HORARIO"],
    title: "Paulo Ferreira",
    subtitle: "Nissan Kicks",
    imageUrl: "https://i.pravatar.cc/150?img=72",
    distanceMeters: 200,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: false,
    metadata: {
      kind: "driver",
      rating: 4.8,
      vehicle: "Nissan Kicks Branco",
      plate: "STU-5678",
      etaMinutes: 4,
      isAvailable: true,
      totalTrips: 720,
    },
  },
  {
    id: "driver-008",
    type: RecommendationType.DRIVER,
    score: {
      interest: 50,
      distance: 82,
      popularity: 72,
      compatibility: 40,
      time: 82,
      recency: 70,
      total: 73,
    },
    reasons: ["DISTANCIA"],
    title: "Lucas Pereira",
    subtitle: "Toyota Yaris",
    imageUrl: "https://i.pravatar.cc/150?img=73",
    distanceMeters: 320,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "driver",
      rating: 4.7,
      vehicle: "Toyota Yaris Prata",
      plate: "VWX-9012",
      etaMinutes: 6,
      isAvailable: true,
      totalTrips: 450,
    },
  },
  {
    id: "driver-009",
    type: RecommendationType.DRIVER,
    score: {
      interest: 50,
      distance: 78,
      popularity: 68,
      compatibility: 40,
      time: 78,
      recency: 65,
      total: 70,
    },
    reasons: ["HORARIO"],
    title: "Gabriel Santos",
    subtitle: "Chevrolet Tracker",
    imageUrl: "https://i.pravatar.cc/150?img=74",
    distanceMeters: 430,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "driver",
      rating: 4.6,
      vehicle: "Chevrolet Tracker Preto",
      plate: "YZA-3456",
      etaMinutes: 8,
      isAvailable: false,
      totalTrips: 310,
    },
  },
  {
    id: "driver-010",
    type: RecommendationType.DRIVER,
    score: {
      interest: 50,
      distance: 73,
      popularity: 62,
      compatibility: 40,
      time: 73,
      recency: 58,
      total: 67,
    },
    reasons: ["DISTANCIA", "HORARIO"],
    title: "Diego Lima",
    subtitle: "Hyundai Creta",
    imageUrl: "https://i.pravatar.cc/150?img=75",
    distanceMeters: 560,
    activityLevel: ActivityLevel.CALMO,
    trending: false,
    metadata: {
      kind: "driver",
      rating: 4.5,
      vehicle: "Hyundai Creta Azul",
      plate: "BCD-7890",
      etaMinutes: 10,
      isAvailable: true,
      totalTrips: 280,
    },
  },
];

const MOCK_REELS: Recommendation[] = [
  {
    id: "reel-001",
    type: RecommendationType.REEL,
    score: {
      interest: 88,
      distance: 60,
      popularity: 85,
      compatibility: 88,
      time: 70,
      recency: 75,
      total: 88,
    },
    reasons: ["INTERESSE", "POPULARIDADE"],
    title: "Sunset na Paulista",
    subtitle: "Giulia Santos",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400",
    distanceMeters: 200,
    activityLevel: ActivityLevel.BOMBANDO,
    trending: true,
    metadata: {
      kind: "reel",
      authorName: "Giulia Santos",
      authorPhoto: "https://i.pravatar.cc/80?img=23",
      likes: 1240,
      comments: 89,
      duration: 30,
      category: "Natureza",
    },
  },
  {
    id: "reel-002",
    type: RecommendationType.REEL,
    score: {
      interest: 82,
      distance: 60,
      popularity: 80,
      compatibility: 82,
      time: 70,
      recency: 75,
      total: 82,
    },
    reasons: ["INTERESSE", "POPULARIDADE"],
    title: "Hamburguer Artesanal",
    subtitle: "Rafael Costa",
    imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400",
    distanceMeters: 300,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: true,
    metadata: {
      kind: "reel",
      authorName: "Rafael Costa",
      authorPhoto: "https://i.pravatar.cc/80?img=12",
      likes: 890,
      comments: 56,
      duration: 15,
      category: "Gastronomia",
    },
  },
  {
    id: "reel-003",
    type: RecommendationType.REEL,
    score: {
      interest: 85,
      distance: 60,
      popularity: 90,
      compatibility: 85,
      time: 70,
      recency: 75,
      total: 85,
    },
    reasons: ["INTERESSE", "POPULARIDADE"],
    title: "DJ Set ao Vivo",
    subtitle: "Camila Ferreira",
    imageUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400",
    distanceMeters: 450,
    activityLevel: ActivityLevel.BOMBANDO,
    trending: true,
    metadata: {
      kind: "reel",
      authorName: "Camila Ferreira",
      authorPhoto: "https://i.pravatar.cc/80?img=26",
      likes: 2100,
      comments: 156,
      duration: 45,
      category: "Musica",
    },
  },
  {
    id: "reel-004",
    type: RecommendationType.REEL,
    score: {
      interest: 75,
      distance: 60,
      popularity: 65,
      compatibility: 75,
      time: 70,
      recency: 75,
      total: 75,
    },
    reasons: ["INTERESSE"],
    title: "Yoga Manha",
    subtitle: "Ana Beatriz",
    imageUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400",
    distanceMeters: 150,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "reel",
      authorName: "Ana Beatriz",
      authorPhoto: "https://i.pravatar.cc/80?img=47",
      likes: 340,
      comments: 23,
      duration: 60,
      category: "Fitness",
    },
  },
  {
    id: "reel-005",
    type: RecommendationType.REEL,
    score: {
      interest: 78,
      distance: 60,
      popularity: 70,
      compatibility: 78,
      time: 70,
      recency: 75,
      total: 78,
    },
    reasons: ["INTERESSE", "POPULARIDADE"],
    title: "Arte de Rua",
    subtitle: "Isabela Mendes",
    imageUrl: "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=400",
    distanceMeters: 600,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: false,
    metadata: {
      kind: "reel",
      authorName: "Isabela Mendes",
      authorPhoto: "https://i.pravatar.cc/80?img=32",
      likes: 670,
      comments: 45,
      duration: 20,
      category: "Arte",
    },
  },
  {
    id: "reel-006",
    type: RecommendationType.REEL,
    score: {
      interest: 80,
      distance: 60,
      popularity: 72,
      compatibility: 80,
      time: 70,
      recency: 75,
      total: 80,
    },
    reasons: ["INTERESSE", "POPULARIDADE"],
    title: "Cafe perfeito",
    subtitle: "Mariana Lopes",
    imageUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400",
    distanceMeters: 100,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: true,
    metadata: {
      kind: "reel",
      authorName: "Mariana Lopes",
      authorPhoto: "https://i.pravatar.cc/80?img=45",
      likes: 520,
      comments: 34,
      duration: 12,
      category: "Gastronomia",
    },
  },
  {
    id: "reel-007",
    type: RecommendationType.REEL,
    score: {
      interest: 72,
      distance: 60,
      popularity: 60,
      compatibility: 72,
      time: 70,
      recency: 75,
      total: 72,
    },
    reasons: ["INTERESSE"],
    title: "Trilha na Serra",
    subtitle: "Pedro Henrique",
    imageUrl: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=400",
    distanceMeters: 3500,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "reel",
      authorName: "Pedro Henrique",
      authorPhoto: "https://i.pravatar.cc/80?img=15",
      likes: 290,
      comments: 18,
      duration: 30,
      category: "Natureza",
    },
  },
  {
    id: "reel-008",
    type: RecommendationType.REEL,
    score: {
      interest: 86,
      distance: 60,
      popularity: 88,
      compatibility: 86,
      time: 70,
      recency: 75,
      total: 86,
    },
    reasons: ["INTERESSE", "POPULARIDADE"],
    title: "Balada Eletronica",
    subtitle: "Camila Ferreira",
    imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400",
    distanceMeters: 800,
    activityLevel: ActivityLevel.BOMBANDO,
    trending: true,
    metadata: {
      kind: "reel",
      authorName: "Camila Ferreira",
      authorPhoto: "https://i.pravatar.cc/80?img=26",
      likes: 1800,
      comments: 120,
      duration: 25,
      category: "Musica",
    },
  },
  {
    id: "reel-009",
    type: RecommendationType.REEL,
    score: {
      interest: 79,
      distance: 60,
      popularity: 70,
      compatibility: 79,
      time: 70,
      recency: 75,
      total: 79,
    },
    reasons: ["INTERESSE", "POPULARIDADE"],
    title: "Por do Sol",
    subtitle: "Thiago Almeida",
    imageUrl: "https://images.unsplash.com/photo-1495616811223-4d98c6e9c869?w=400",
    distanceMeters: 500,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: false,
    metadata: {
      kind: "reel",
      authorName: "Thiago Almeida",
      authorPhoto: "https://i.pravatar.cc/80?img=18",
      likes: 450,
      comments: 28,
      duration: 20,
      category: "Natureza",
    },
  },
  {
    id: "reel-010",
    type: RecommendationType.REEL,
    score: {
      interest: 77,
      distance: 60,
      popularity: 65,
      compatibility: 77,
      time: 70,
      recency: 75,
      total: 77,
    },
    reasons: ["INTERESSE"],
    title: "Sushi Masterclass",
    subtitle: "Pedro Henrique",
    imageUrl: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400",
    distanceMeters: 250,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "reel",
      authorName: "Pedro Henrique",
      authorPhoto: "https://i.pravatar.cc/80?img=15",
      likes: 380,
      comments: 22,
      duration: 40,
      category: "Gastronomia",
    },
  },
  {
    id: "reel-011",
    type: RecommendationType.REEL,
    score: {
      interest: 74,
      distance: 60,
      popularity: 72,
      compatibility: 74,
      time: 70,
      recency: 75,
      total: 74,
    },
    reasons: ["INTERESSE", "POPULARIDADE"],
    title: "Skate na Paulista",
    subtitle: "Felipe Rocha",
    imageUrl: "https://images.unsplash.com/photo-1564429238961-bf8d20832e43?w=400",
    distanceMeters: 180,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: false,
    metadata: {
      kind: "reel",
      authorName: "Felipe Rocha",
      authorPhoto: "https://i.pravatar.cc/80?img=53",
      likes: 620,
      comments: 38,
      duration: 18,
      category: "Esporte",
    },
  },
  {
    id: "reel-012",
    type: RecommendationType.REEL,
    score: {
      interest: 70,
      distance: 60,
      popularity: 60,
      compatibility: 70,
      time: 70,
      recency: 75,
      total: 70,
    },
    reasons: ["INTERESSE"],
    title: "Pintura Digital",
    subtitle: "Isabela Mendes",
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400",
    distanceMeters: 520,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "reel",
      authorName: "Isabela Mendes",
      authorPhoto: "https://i.pravatar.cc/80?img=32",
      likes: 280,
      comments: 15,
      duration: 35,
      category: "Arte",
    },
  },
  {
    id: "reel-013",
    type: RecommendationType.REEL,
    score: {
      interest: 76,
      distance: 60,
      popularity: 68,
      compatibility: 76,
      time: 70,
      recency: 75,
      total: 76,
    },
    reasons: ["INTERESSE", "POPULARIDADE"],
    title: "Smoothie Detox",
    subtitle: "Giulia Santos",
    imageUrl: "https://images.unsplash.com/photo-1502741224143-90386d7f8c82?w=400",
    distanceMeters: 150,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "reel",
      authorName: "Giulia Santos",
      authorPhoto: "https://i.pravatar.cc/80?img=23",
      likes: 410,
      comments: 29,
      duration: 10,
      category: "Gastronomia",
    },
  },
  {
    id: "reel-014",
    type: RecommendationType.REEL,
    score: {
      interest: 73,
      distance: 60,
      popularity: 62,
      compatibility: 73,
      time: 70,
      recency: 75,
      total: 73,
    },
    reasons: ["INTERESSE"],
    title: "Tattoo Art",
    subtitle: "Rafael Costa",
    imageUrl: "https://images.unsplash.com/photo-1611501275019-9b5cda994e8d?w=400",
    distanceMeters: 350,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "reel",
      authorName: "Rafael Costa",
      authorPhoto: "https://i.pravatar.cc/80?img=12",
      likes: 320,
      comments: 20,
      duration: 22,
      category: "Arte",
    },
  },
  {
    id: "reel-015",
    type: RecommendationType.REEL,
    score: {
      interest: 81,
      distance: 60,
      popularity: 78,
      compatibility: 81,
      time: 70,
      recency: 75,
      total: 81,
    },
    reasons: ["INTERESSE", "POPULARIDADE"],
    title: "Vida Noturna SP",
    subtitle: "Camila Ferreira",
    imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400",
    distanceMeters: 400,
    activityLevel: ActivityLevel.BOMBANDO,
    trending: true,
    metadata: {
      kind: "reel",
      authorName: "Camila Ferreira",
      authorPhoto: "https://i.pravatar.cc/80?img=26",
      likes: 1560,
      comments: 98,
      duration: 28,
      category: "Musica",
    },
  },
  {
    id: "reel-016",
    type: RecommendationType.REEL,
    score: {
      interest: 68,
      distance: 60,
      popularity: 58,
      compatibility: 68,
      time: 70,
      recency: 75,
      total: 68,
    },
    reasons: ["INTERESSE"],
    title: "Crossfit Challenge",
    subtitle: "Felipe Rocha",
    imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400",
    distanceMeters: 950,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: false,
    metadata: {
      kind: "reel",
      authorName: "Felipe Rocha",
      authorPhoto: "https://i.pravatar.cc/80?img=53",
      likes: 250,
      comments: 12,
      duration: 45,
      category: "Fitness",
    },
  },
  {
    id: "reel-017",
    type: RecommendationType.REEL,
    score: {
      interest: 71,
      distance: 60,
      popularity: 63,
      compatibility: 71,
      time: 70,
      recency: 75,
      total: 71,
    },
    reasons: ["INTERESSE"],
    title: "Street Food Tour",
    subtitle: "Ana Beatriz",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
    distanceMeters: 680,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "reel",
      authorName: "Ana Beatriz",
      authorPhoto: "https://i.pravatar.cc/80?img=47",
      likes: 310,
      comments: 19,
      duration: 32,
      category: "Gastronomia",
    },
  },
  {
    id: "reel-018",
    type: RecommendationType.REEL,
    score: {
      interest: 77,
      distance: 60,
      popularity: 74,
      compatibility: 77,
      time: 70,
      recency: 75,
      total: 77,
    },
    reasons: ["INTERESSE", "POPULARIDADE"],
    title: "Capoeira na Praca",
    subtitle: "Mariana Lopes",
    imageUrl: "https://images.unsplash.com/photo-1547153760-18fc86c30218?w=400",
    distanceMeters: 300,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: false,
    metadata: {
      kind: "reel",
      authorName: "Mariana Lopes",
      authorPhoto: "https://i.pravatar.cc/80?img=45",
      likes: 480,
      comments: 32,
      duration: 38,
      category: "Esporte",
    },
  },
  {
    id: "reel-019",
    type: RecommendationType.REEL,
    score: {
      interest: 69,
      distance: 60,
      popularity: 58,
      compatibility: 69,
      time: 70,
      recency: 75,
      total: 69,
    },
    reasons: ["INTERESSE"],
    title: "Pao Artesanal",
    subtitle: "Thiago Almeida",
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400",
    distanceMeters: 450,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "reel",
      authorName: "Thiago Almeida",
      authorPhoto: "https://i.pravatar.cc/80?img=18",
      likes: 220,
      comments: 14,
      duration: 25,
      category: "Gastronomia",
    },
  },
  {
    id: "reel-020",
    type: RecommendationType.REEL,
    score: {
      interest: 83,
      distance: 60,
      popularity: 82,
      compatibility: 83,
      time: 70,
      recency: 75,
      total: 83,
    },
    reasons: ["INTERESSE", "POPULARIDADE"],
    title: "Festival de Luz",
    subtitle: "Isabela Mendes",
    imageUrl: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=400",
    distanceMeters: 700,
    activityLevel: ActivityLevel.BOMBANDO,
    trending: true,
    metadata: {
      kind: "reel",
      authorName: "Isabela Mendes",
      authorPhoto: "https://i.pravatar.cc/80?img=32",
      likes: 1340,
      comments: 87,
      duration: 20,
      category: "Festival",
    },
  },
];

const MOCK_PLACES: Recommendation[] = [
  {
    id: "place-001",
    type: RecommendationType.PLACE,
    score: {
      interest: 85,
      distance: 90,
      popularity: 82,
      compatibility: 80,
      time: 85,
      recency: 80,
      total: 84,
    },
    reasons: ["DISTANCIA", "POPULARIDADE"],
    title: "Parque Ibirapuera",
    subtitle: "Parque & Natureza",
    imageUrl: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=400",
    distanceMeters: 450,
    activityLevel: ActivityLevel.BOMBANDO,
    trending: true,
    metadata: {
      kind: "place",
      category: "Parque",
      rating: 4.8,
      checkInCount: 456,
      isOpen: true,
      priceRange: null,
    },
  },
  {
    id: "place-002",
    type: RecommendationType.PLACE,
    score: {
      interest: 78,
      distance: 85,
      popularity: 75,
      compatibility: 75,
      time: 78,
      recency: 75,
      total: 77,
    },
    reasons: ["DISTANCIA", "POPULARIDADE"],
    title: "Av. Paulista",
    subtitle: "Ponto Turistico",
    imageUrl: "https://images.unsplash.com/photo-1543059080-f9b12722e094?w=400",
    distanceMeters: 200,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: true,
    metadata: {
      kind: "place",
      category: "Ponto Turistico",
      rating: 4.7,
      checkInCount: 892,
      isOpen: true,
      priceRange: null,
    },
  },
  {
    id: "place-003",
    type: RecommendationType.PLACE,
    score: {
      interest: 72,
      distance: 70,
      popularity: 68,
      compatibility: 70,
      time: 72,
      recency: 70,
      total: 70,
    },
    reasons: ["INTERESSE", "HORARIO"],
    title: "Cafe Central",
    subtitle: "Cafe & Relax",
    imageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=400",
    distanceMeters: 150,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: false,
    metadata: {
      kind: "place",
      category: "Cafe",
      rating: 4.7,
      checkInCount: 234,
      isOpen: true,
      priceRange: "$$",
    },
  },
  {
    id: "place-004",
    type: RecommendationType.PLACE,
    score: {
      interest: 75,
      distance: 80,
      popularity: 72,
      compatibility: 72,
      time: 75,
      recency: 72,
      total: 73,
    },
    reasons: ["POPULARIDADE", "LOCAL"],
    title: "Pinacoteca",
    subtitle: "Museu & Arte",
    imageUrl: "https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?w=400",
    distanceMeters: 350,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "place",
      category: "Museu",
      rating: 4.6,
      checkInCount: 156,
      isOpen: true,
      priceRange: "$",
    },
  },
  {
    id: "place-005",
    type: RecommendationType.PLACE,
    score: {
      interest: 80,
      distance: 75,
      popularity: 78,
      compatibility: 75,
      time: 80,
      recency: 78,
      total: 77,
    },
    reasons: ["POPULARIDADE", "HORARIO"],
    title: "Mercado Municipal",
    subtitle: "Comida & Cultura",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
    distanceMeters: 600,
    activityLevel: ActivityLevel.BOMBANDO,
    trending: true,
    metadata: {
      kind: "place",
      category: "Mercado",
      rating: 4.5,
      checkInCount: 567,
      isOpen: true,
      priceRange: "$",
    },
  },
  {
    id: "place-006",
    type: RecommendationType.PLACE,
    score: {
      interest: 68,
      distance: 65,
      popularity: 65,
      compatibility: 68,
      time: 68,
      recency: 65,
      total: 67,
    },
    reasons: ["COMPATIBILIDADE", "LOCAL"],
    title: "Livraria Cultura",
    subtitle: "Livraria & Cafe",
    imageUrl: "https://images.unsplash.com/photo-1526243741027-444d633d7365?w=400",
    distanceMeters: 400,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "place",
      category: "Livraria",
      rating: 4.4,
      checkInCount: 123,
      isOpen: true,
      priceRange: "$$",
    },
  },
  {
    id: "place-007",
    type: RecommendationType.PLACE,
    score: {
      interest: 74,
      distance: 72,
      popularity: 70,
      compatibility: 72,
      time: 74,
      recency: 70,
      total: 72,
    },
    reasons: ["HORARIO", "INTERESSE"],
    title: "Parque Villa-Lobos",
    subtitle: "Parque & Ciclovia",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400",
    distanceMeters: 800,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: false,
    metadata: {
      kind: "place",
      category: "Parque",
      rating: 4.3,
      checkInCount: 289,
      isOpen: true,
      priceRange: null,
    },
  },
  {
    id: "place-008",
    type: RecommendationType.PLACE,
    score: {
      interest: 70,
      distance: 60,
      popularity: 66,
      compatibility: 70,
      time: 70,
      recency: 66,
      total: 68,
    },
    reasons: ["COMPATIBILIDADE", "DISTANCIA"],
    title: "CCBB",
    subtitle: "Centro Cultural",
    imageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400",
    distanceMeters: 650,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "place",
      category: "Centro Cultural",
      rating: 4.5,
      checkInCount: 198,
      isOpen: true,
      priceRange: null,
    },
  },
  {
    id: "place-009",
    type: RecommendationType.PLACE,
    score: {
      interest: 76,
      distance: 78,
      popularity: 74,
      compatibility: 73,
      time: 76,
      recency: 74,
      total: 74,
    },
    reasons: ["POPULARIDADE", "HORARIO"],
    title: "Shopping Ibirapuera",
    subtitle: "Shopping & Entretenimento",
    imageUrl: "https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?w=400",
    distanceMeters: 500,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: false,
    metadata: {
      kind: "place",
      category: "Shopping",
      rating: 4.4,
      checkInCount: 678,
      isOpen: true,
      priceRange: "$$$",
    },
  },
  {
    id: "place-010",
    type: RecommendationType.PLACE,
    score: {
      interest: 65,
      distance: 55,
      popularity: 60,
      compatibility: 65,
      time: 65,
      recency: 60,
      total: 62,
    },
    reasons: ["DISTANCIA", "LOCAL"],
    title: "Praca da Republica",
    subtitle: "Praca & Eventos",
    imageUrl: "https://images.unsplash.com/photo-1496568816309-51d7c20e3b21?w=400",
    distanceMeters: 900,
    activityLevel: ActivityLevel.MODERADO,
    trending: false,
    metadata: {
      kind: "place",
      category: "Praca",
      rating: 4.2,
      checkInCount: 145,
      isOpen: true,
      priceRange: null,
    },
  },
];

export const mockRecommendations: Recommendation[] = [
  ...MOCK_PEOPLE,
  ...MOCK_EVENTS,
  ...MOCK_BUSINESSES,
  ...MOCK_DRIVERS,
  ...MOCK_REELS,
  ...MOCK_PLACES,
];

export const mockTrendingPlaces: TrendingPlace[] = [
  {
    id: "tp-001",
    name: "Parque Ibirapuera",
    category: "Parque",
    imageUrl: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=400",
    lat: -23.5874,
    lng: -46.6574,
    distanceMeters: 450,
    activityLevel: ActivityLevel.BOMBANDO,
    checkInCount: 456,
    trending: true,
  },
  {
    id: "tp-002",
    name: "Av. Paulista",
    category: "Ponto Turistico",
    imageUrl: "https://images.unsplash.com/photo-1543059080-f9b12722e094?w=400",
    lat: -23.5632,
    lng: -46.6542,
    distanceMeters: 200,
    activityLevel: ActivityLevel.EM_ALTA,
    checkInCount: 892,
    trending: true,
  },
  {
    id: "tp-003",
    name: "Mercado Municipal",
    category: "Mercado",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
    lat: -23.5432,
    lng: -46.6292,
    distanceMeters: 600,
    activityLevel: ActivityLevel.BOMBANDO,
    checkInCount: 567,
    trending: true,
  },
  {
    id: "tp-004",
    name: "Pinacoteca",
    category: "Museu",
    imageUrl: "https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?w=400",
    lat: -23.5316,
    lng: -46.6385,
    distanceMeters: 350,
    activityLevel: ActivityLevel.MODERADO,
    checkInCount: 156,
    trending: false,
  },
  {
    id: "tp-005",
    name: "Shopping Ibirapuera",
    category: "Shopping",
    imageUrl: "https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?w=400",
    lat: -23.5878,
    lng: -46.6542,
    distanceMeters: 500,
    activityLevel: ActivityLevel.EM_ALTA,
    checkInCount: 678,
    trending: false,
  },
];

export const mockTrendingEvents: TrendingEvent[] = [
  {
    id: "te-001",
    name: "Sunset no Ibirapuera",
    date: new Date().toISOString(),
    location: "Parque Ibirapuera",
    coverUrl: "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=400",
    category: "Musica",
    interestedCount: 234,
    attendingCount: 156,
    activityLevel: ActivityLevel.BOMBANDO,
    trending: true,
  },
  {
    id: "te-002",
    name: "Festival Eletronico",
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    location: "Autodromo de Interlagos",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400",
    category: "Musica",
    interestedCount: 1250,
    attendingCount: 890,
    activityLevel: ActivityLevel.MUITO_CHEIO,
    trending: true,
  },
  {
    id: "te-003",
    name: "Tech Meetup SP",
    date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    location: "WeWork Faria Lima",
    coverUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400",
    category: "Tecnologia",
    interestedCount: 89,
    attendingCount: 67,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: true,
  },
  {
    id: "te-004",
    name: "Feira Gastronomica",
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    location: "Praca da Republica",
    coverUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
    category: "Gastronomia",
    interestedCount: 312,
    attendingCount: 198,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: false,
  },
  {
    id: "te-005",
    name: "Corrida de Rua 5K",
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    location: "Marginal Pinheiros",
    coverUrl: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=400",
    category: "Esporte",
    interestedCount: 234,
    attendingCount: 178,
    activityLevel: ActivityLevel.EM_ALTA,
    trending: false,
  },
];

export const mockTrendingBusinesses: TrendingBusiness[] = [
  {
    id: "tb-001",
    name: "Cafe Central",
    category: "Cafe",
    logo: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=400",
    rating: 4.7,
    reviewCount: 234,
    distanceMeters: 150,
    activityLevel: ActivityLevel.EM_ALTA,
    offerCount: 2,
    trending: true,
  },
  {
    id: "tb-002",
    name: "Sushi Tanaka",
    category: "Restaurante",
    logo: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400",
    rating: 4.8,
    reviewCount: 312,
    distanceMeters: 180,
    activityLevel: ActivityLevel.BOMBANDO,
    offerCount: 1,
    trending: true,
  },
  {
    id: "tb-003",
    name: "Burger House",
    category: "Lanchonete",
    logo: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400",
    rating: 4.5,
    reviewCount: 189,
    distanceMeters: 300,
    activityLevel: ActivityLevel.BOMBANDO,
    offerCount: 3,
    trending: true,
  },
  {
    id: "tb-004",
    name: "CrossFit Arena",
    category: "Academia",
    logo: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400",
    rating: 4.6,
    reviewCount: 189,
    distanceMeters: 950,
    activityLevel: ActivityLevel.BOMBANDO,
    offerCount: 3,
    trending: false,
  },
  {
    id: "tb-005",
    name: "Bar do Ze",
    category: "Bar",
    logo: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=400",
    rating: 4.4,
    reviewCount: 267,
    distanceMeters: 700,
    activityLevel: ActivityLevel.EM_ALTA,
    offerCount: 0,
    trending: false,
  },
];

export const mockTrendingPeople: TrendingPerson[] = [
  {
    id: "tp-001",
    name: "Giulia Santos",
    handle: "giulia.s",
    photoUrl: "https://i.pravatar.cc/150?img=23",
    profession: "Designer UX",
    age: 28,
    compatibilityPercent: 92,
    distanceMeters: 350,
    isOnline: true,
    mutualConnections: 5,
  },
  {
    id: "tp-002",
    name: "Rafael Costa",
    handle: "rafael.c",
    photoUrl: "https://i.pravatar.cc/150?img=12",
    profession: "Desenvolvedor",
    age: 31,
    compatibilityPercent: 87,
    distanceMeters: 120,
    isOnline: true,
    mutualConnections: 3,
  },
  {
    id: "tp-003",
    name: "Mariana Lopes",
    handle: "mariana.l",
    photoUrl: "https://i.pravatar.cc/150?img=45",
    profession: "Musicista",
    age: 26,
    compatibilityPercent: 82,
    distanceMeters: 280,
    isOnline: true,
    mutualConnections: 4,
  },
  {
    id: "tp-004",
    name: "Ana Beatriz",
    handle: "ana.b",
    photoUrl: "https://i.pravatar.cc/150?img=47",
    profession: "Fotografa",
    age: 25,
    compatibilityPercent: 78,
    distanceMeters: 680,
    isOnline: false,
    mutualConnections: 2,
  },
  {
    id: "tp-005",
    name: "Camila Ferreira",
    handle: "camila.f",
    photoUrl: "https://i.pravatar.cc/150?img=26",
    profession: "DJ & Produtora",
    age: 27,
    compatibilityPercent: 72,
    distanceMeters: 900,
    isOnline: true,
    mutualConnections: 8,
  },
];

export const mockTrendingDrivers: TrendingDriver[] = [
  {
    id: "td-001",
    name: "Marcos Silva",
    photo: "https://i.pravatar.cc/150?img=68",
    rating: 4.9,
    vehicle: "Toyota Corolla Prata",
    etaMinutes: 3,
    distanceMeters: 120,
    isAvailable: true,
    totalTrips: 1250,
  },
  {
    id: "td-002",
    name: "Paulo Ferreira",
    photo: "https://i.pravatar.cc/150?img=72",
    rating: 4.8,
    vehicle: "Nissan Kicks Branco",
    etaMinutes: 4,
    distanceMeters: 200,
    isAvailable: true,
    totalTrips: 720,
  },
  {
    id: "td-003",
    name: "Joao Santos",
    photo: "https://i.pravatar.cc/150?img=52",
    rating: 4.8,
    vehicle: "Honda Civic Preto",
    etaMinutes: 5,
    distanceMeters: 250,
    isAvailable: true,
    totalTrips: 890,
  },
  {
    id: "td-004",
    name: "Lucas Pereira",
    photo: "https://i.pravatar.cc/150?img=73",
    rating: 4.7,
    vehicle: "Toyota Yaris Prata",
    etaMinutes: 6,
    distanceMeters: 320,
    isAvailable: true,
    totalTrips: 450,
  },
  {
    id: "td-005",
    name: "Carlos Mendes",
    photo: "https://i.pravatar.cc/150?img=57",
    rating: 4.7,
    vehicle: "Hyundai HB20 Branco",
    etaMinutes: 7,
    distanceMeters: 380,
    isAvailable: true,
    totalTrips: 560,
  },
];
