import type { Reel, ReelCategoryValue } from "./reel-types";

/* =========================================================
   reel-mocks.ts — Reels mockados ancorados nos ids reais do
   ecossistema Connexy (Fase 3A).
   Entidades resolvíveis nas telas de detalhe:
     - pessoas:   /perfil/$id   (beatriz, rafael, juliana, …)
     - locais:    /local/$id    (cafe-central, sunset-parque,
                                  burger-house, vinil-store)
     - negócios:  /business/$businessId (b1..b6)
     - eventos:   /event/$eventId      (evt-1, evt-2)
     - motoristas:/ride          (d1..d3)
   Alguns reels têm exatamente 2 vídeos (campo `videos`) para
   demonstrar os indicadores de paginação do player.
========================================================= */

export function findReelById(id: string): Reel | undefined {
  return MOCK_REELS.find((reel) => reel.id === id);
}

export const MOCK_REELS: Reel[] = [
  {
    id: "reel-001",
    videoUrl: "https://videos.pexels.com/video-files/3571264/3571264-uhd_2560_1440_30fps.mp4",
    videos: [
      "https://videos.pexels.com/video-files/3571264/3571264-uhd_2560_1440_30fps.mp4",
      "https://videos.pexels.com/video-files/1721306/1721306-hd_1920_1080_24fps.mp4",
    ],
    posterUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800",
    caption: "Vibes de vinil na tarde de domingo. Nada supera o som analógico!",
    category: "PERSON" as ReelCategoryValue,
    author: {
      id: "beatriz",
      name: "Beatriz",
      handle: "@bea.vinil",
      photoUrl: "https://i.pravatar.cc/200?img=47",
      verified: false,
      profession: "DJ & Colecionadora",
      isFollowing: false,
    },
    music: {
      id: "music-001",
      title: "Águas de Março",
      artist: "Antônio Carlos Jobim",
      duration: 210,
      coverUrl: "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=200",
    },
    location: {
      id: "vinil-store",
      name: "Vinil & Cia",
      address: "Rua Cardeal Arcoverde, 420, Pinheiros",
      lat: -23.5628,
      lng: -46.6912,
      category: "Loja de Discos",
      distanceMeters: 900,
    },
    business: null,
    event: null,
    driver: null,
    stats: { likes: 2340, comments: 87, shares: 156, saves: 230, views: 18500, duration: 32 },
    hashtags: ["#vinil", "#músicaanáloga", "#sampa", "#vinilstore"],
    taggedUserIds: ["juliana"],
    createdAt: "2026-08-07T14:30:00Z",
    likedByMe: false,
    savedByMe: false,
  },
  {
    id: "reel-002",
    videoUrl: "https://videos.pexels.com/video-files/4763824/4763824-uhd_2732_1440_25fps.mp4",
    posterUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800",
    caption: "Corrida matinal feita. Escala no Café Central pra fechar com chave de ouro!",
    category: "PERSON" as ReelCategoryValue,
    author: {
      id: "rafael",
      name: "Rafael",
      handle: "@rafa.run",
      photoUrl: "https://i.pravatar.cc/200?img=13",
      verified: true,
      profession: "Desenvolvedor & Atleta",
      isFollowing: true,
    },
    music: {
      id: "music-002",
      title: "Run the World",
      artist: "Beyoncé",
      duration: 230,
      coverUrl: null,
    },
    location: {
      id: "cafe-central",
      name: "Café Central",
      address: "Rua Augusta, 1200, Consolação",
      lat: -23.552,
      lng: -46.6612,
      category: "Cafeteria",
      distanceMeters: 200,
    },
    business: null,
    event: null,
    driver: null,
    stats: { likes: 1890, comments: 134, shares: 98, saves: 175, views: 14200, duration: 28 },
    hashtags: ["#corrida", "#runner", "#cafezinho", "#healthylife"],
    taggedUserIds: ["pedro-henrique"],
    createdAt: "2026-08-07T07:15:00Z",
    likedByMe: false,
    savedByMe: false,
  },
  {
    id: "reel-003",
    videoUrl: "https://videos.pexels.com/video-files/4816205/4816205-uhd_2560_1440_30fps.mp4",
    posterUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800",
    caption: "O aroma perfeito de um espresso recém-passado. Venha sentir essa experiência!",
    category: "BUSINESS" as ReelCategoryValue,
    author: {
      id: "b2",
      name: "Café Aroma",
      handle: "@cafearomasp",
      photoUrl: "https://i.pravatar.cc/200?img=60",
      verified: true,
      profession: null,
      isFollowing: false,
    },
    music: {
      id: "music-003",
      title: "Lovely Day",
      artist: "Bill Withers",
      duration: 250,
      coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=200",
    },
    location: {
      id: "cafe-central",
      name: "Café Central",
      address: "Rua Augusta, 1200, Consolação",
      lat: -23.552,
      lng: -46.6612,
      category: "Cafeteria",
      distanceMeters: 200,
    },
    business: {
      id: "b2",
      name: "Café Aroma",
      logo: "https://images.unsplash.com/photo-1559496417-e7f25cb247f3?w=200",
      category: "Cafeteria",
      rating: 4.8,
      reviewCount: 210,
      isFollowing: false,
      offers: [
        {
          id: "offer-003",
          title: "Combo café",
          description: "Leve 1 café pague 1 em combo da manhã",
          discountPercent: 100,
          validUntil: "2026-08-31T23:59:59Z",
        },
      ],
    },
    event: null,
    driver: null,
    stats: { likes: 4520, comments: 198, shares: 445, saves: 310, views: 42000, duration: 20 },
    hashtags: ["#cafécultural", "#espresso", "#sp", "#cafezinho"],
    taggedUserIds: [],
    createdAt: "2026-08-06T16:45:00Z",
    likedByMe: false,
    savedByMe: false,
  },
  {
    id: "reel-004",
    videoUrl: "https://videos.pexels.com/video-files/3571264/3571264-hd_1920_1080_30fps.mp4",
    posterUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800",
    caption: "Menu de inverno chegando no Bistrô. Risoto de cogumelos é o destaque!",
    category: "BUSINESS" as ReelCategoryValue,
    author: {
      id: "b1",
      name: "Bistrô Paulista",
      handle: "@bistropaulista",
      photoUrl: "https://i.pravatar.cc/200?img=59",
      verified: true,
      profession: null,
      isFollowing: false,
    },
    music: {
      id: "music-004",
      title: "That's Amore",
      artist: "Dean Martin",
      duration: 190,
      coverUrl: null,
    },
    location: null,
    business: {
      id: "b1",
      name: "Bistrô Paulista",
      logo: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=200",
      category: "Restaurante",
      rating: 4.7,
      reviewCount: 320,
      isFollowing: false,
      offers: [
        {
          id: "offer-001",
          title: "Happy Hour",
          description: "20% em todas as bebidas das 17h às 20h",
          discountPercent: 20,
          validUntil: "2026-12-31T23:59:59Z",
        },
      ],
    },
    event: null,
    driver: null,
    stats: { likes: 3200, comments: 142, shares: 280, saves: 290, views: 28000, duration: 45 },
    hashtags: ["#bistrô", "#gastronomia", "#risoto", "#avpaulista"],
    taggedUserIds: [],
    createdAt: "2026-08-05T19:20:00Z",
    likedByMe: false,
    savedByMe: false,
  },
  {
    id: "reel-005",
    videoUrl: "https://videos.pexels.com/video-files/1093662/1093662-hd_1920_1080_30fps.mp4",
    videos: [
      "https://videos.pexels.com/video-files/1093662/1093662-hd_1920_1080_30fps.mp4",
      "https://videos.pexels.com/video-files/1721296/1721296-hd_1920_1080_24fps.mp4",
    ],
    posterUrl: "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800",
    caption: "Quarteto de jazz ao vivo amanhã no Bistrô. Reservas abertas!",
    category: "EVENT" as ReelCategoryValue,
    author: {
      id: "evt-1",
      name: "Noite de Jazz",
      handle: "@noitedejazz",
      photoUrl: "https://i.pravatar.cc/200?img=45",
      verified: true,
      profession: null,
      isFollowing: false,
    },
    music: {
      id: "music-005",
      title: "Take Five",
      artist: "Dave Brubeck",
      duration: 324,
      coverUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=200",
    },
    location: null,
    business: null,
    event: {
      id: "evt-1",
      name: "Noite de Jazz",
      date: "2026-08-08T20:00:00Z",
      location: "Bistrô Paulista — Salão principal",
      coverUrl: "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800",
      interestedCount: 890,
      attendingCount: 345,
      isInterested: false,
      isAttending: false,
      checkedIn: false,
    },
    driver: null,
    stats: { likes: 3780, comments: 165, shares: 410, saves: 275, views: 35000, duration: 25 },
    hashtags: ["#jazz", "#aovivo", "#spevents", "#bistrôpaulista"],
    taggedUserIds: ["ana-clara"],
    createdAt: "2026-08-06T12:00:00Z",
    likedByMe: false,
    savedByMe: false,
  },
  {
    id: "reel-006",
    videoUrl: "https://videos.pexels.com/video-files/3129671/3129671-uhd_2560_1440_30fps.mp4",
    posterUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800",
    caption: "Degustação guiada dos melhores vinhos importados no Hotel Luxe. Vem!",
    category: "EVENT" as ReelCategoryValue,
    author: {
      id: "evt-2",
      name: "Degustação de Vinhos",
      handle: "@degustacaovinhos",
      photoUrl: "https://i.pravatar.cc/200?img=56",
      verified: true,
      profession: null,
      isFollowing: false,
    },
    music: {
      id: "music-006",
      title: "Aquarela",
      artist: "Toquinho",
      duration: 210,
      coverUrl: null,
    },
    location: null,
    business: null,
    event: {
      id: "evt-2",
      name: "Degustação de Vinhos",
      date: "2026-08-07T19:00:00Z",
      location: "Hotel Luxe",
      coverUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800",
      interestedCount: 1240,
      attendingCount: 890,
      isInterested: false,
      isAttending: false,
      checkedIn: false,
    },
    driver: null,
    stats: { likes: 4100, comments: 178, shares: 320, saves: 305, views: 48000, duration: 35 },
    hashtags: ["#degustação", "#vinhos", "#enoturismo", "#hotelluxe"],
    taggedUserIds: [],
    createdAt: "2026-08-06T10:30:00Z",
    likedByMe: false,
    savedByMe: false,
  },
  {
    id: "reel-007",
    videoUrl: "https://videos.pexels.com/video-files/1448735/1448735-hd_1920_1080_25fps.mp4",
    posterUrl: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800",
    caption: "Grãos especiais, torra artesanal e boa trilha sonora. Café Central, a 200m de você!",
    category: "PLACE" as ReelCategoryValue,
    author: {
      id: "cafe-central",
      name: "Café Central",
      handle: "@cafecentralsp",
      photoUrl: "https://i.pravatar.cc/200?img=60",
      verified: true,
      profession: null,
      isFollowing: false,
    },
    music: {
      id: "music-007",
      title: "Águas de Primavera",
      artist: "Toquinho & Vinícius",
      duration: 195,
      coverUrl: null,
    },
    location: {
      id: "cafe-central",
      name: "Café Central",
      address: "Rua Augusta, 1200, Consolação",
      lat: -23.552,
      lng: -46.6612,
      category: "Cafeteria",
      distanceMeters: 200,
    },
    business: null,
    event: null,
    driver: null,
    stats: { likes: 2870, comments: 112, shares: 230, saves: 265, views: 22000, duration: 40 },
    hashtags: ["#cafécentral", "#espresso", "#grãos", "#perto de você"],
    taggedUserIds: ["luana"],
    createdAt: "2026-08-07T08:45:00Z",
    likedByMe: false,
    savedByMe: false,
  },
  {
    id: "reel-008",
    videoUrl: "https://videos.pexels.com/video-files/3191393/3191393-uhd_2560_1440_30fps.mp4",
    posterUrl: "https://images.unsplash.com/photo-1483412033650-1015ddeb83d1?w=800",
    caption: "Os melhores discos de vinil da cidade. Encontre seu som no Vinil & Cia!",
    category: "PLACE" as ReelCategoryValue,
    author: {
      id: "vinil-store",
      name: "Vinil & Cia",
      handle: "@vilinaciashop",
      photoUrl: "https://i.pravatar.cc/200?img=50",
      verified: true,
      profession: null,
      isFollowing: true,
    },
    music: {
      id: "music-008",
      title: "Take Five",
      artist: "Dave Brubeck",
      duration: 324,
      coverUrl: null,
    },
    location: {
      id: "vinil-store",
      name: "Vinil & Cia",
      address: "Rua Cardeal Arcoverde, 420, Pinheiros",
      lat: -23.5628,
      lng: -46.6912,
      category: "Loja de Discos",
      distanceMeters: 900,
    },
    business: null,
    event: null,
    driver: null,
    stats: { likes: 4980, comments: 195, shares: 480, saves: 295, views: 52000, duration: 38 },
    hashtags: ["#vinil", "#colecionáveis", "#lojadevinis", "#música"],
    taggedUserIds: ["thiago"],
    createdAt: "2026-08-05T15:10:00Z",
    likedByMe: false,
    savedByMe: false,
  },
  {
    id: "reel-009",
    videoUrl: "https://videos.pexels.com/video-files/5765828/5765828-hd_1920_1080_25fps.mp4",
    posterUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800",
    caption: "Combo café: leve 1 pague 1 em combo da manhã. Só até o fim do mês!",
    category: "OFFER" as ReelCategoryValue,
    author: {
      id: "b2",
      name: "Café Aroma",
      handle: "@cafearomasp",
      photoUrl: "https://i.pravatar.cc/200?img=60",
      verified: true,
      profession: null,
      isFollowing: false,
    },
    music: {
      id: "music-009",
      title: "Lovely Day",
      artist: "Bill Withers",
      duration: 250,
      coverUrl: null,
    },
    location: {
      id: "cafe-central",
      name: "Café Central",
      address: "Rua Augusta, 1200, Consolação",
      lat: -23.552,
      lng: -46.6612,
      category: "Cafeteria",
      distanceMeters: 200,
    },
    business: {
      id: "b2",
      name: "Café Aroma",
      logo: "https://images.unsplash.com/photo-1559496417-e7f25cb247f3?w=200",
      category: "Cafeteria",
      rating: 4.8,
      reviewCount: 210,
      isFollowing: false,
      offers: [
        {
          id: "offer-003",
          title: "Combo café",
          description: "Leve 1 café pague 1 em combo da manhã",
          discountPercent: 100,
          validUntil: "2026-08-31T23:59:59Z",
        },
      ],
    },
    event: null,
    driver: null,
    stats: { likes: 3560, comments: 180, shares: 390, saves: 285, views: 39000, duration: 18 },
    hashtags: ["#combo", "#cafezinho", "#oferta", "#bogo"],
    taggedUserIds: [],
    createdAt: "2026-08-07T11:00:00Z",
    likedByMe: false,
    savedByMe: false,
  },
  {
    id: "reel-010",
    videoUrl: "https://videos.pexels.com/video-files/3015510/3015510-uhd_2560_1440_25fps.mp4",
    posterUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
    caption: "Happy hour toda tarde no Bistrô Paulista. 20% OFF em bebidas das 17h às 20h!",
    category: "OFFER" as ReelCategoryValue,
    author: {
      id: "b1",
      name: "Bistrô Paulista",
      handle: "@bistropaulista",
      photoUrl: "https://i.pravatar.cc/200?img=59",
      verified: true,
      profession: null,
      isFollowing: false,
    },
    music: {
      id: "music-010",
      title: "Happy",
      artist: "Pharrell Williams",
      duration: 240,
      coverUrl: null,
    },
    location: null,
    business: {
      id: "b1",
      name: "Bistrô Paulista",
      logo: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=200",
      category: "Restaurante",
      rating: 4.7,
      reviewCount: 320,
      isFollowing: false,
      offers: [
        {
          id: "offer-001",
          title: "Happy Hour",
          description: "20% em todas as bebidas das 17h às 20h",
          discountPercent: 20,
          validUntil: "2026-12-31T23:59:59Z",
        },
      ],
    },
    event: null,
    driver: null,
    stats: { likes: 2890, comments: 95, shares: 390, saves: 180, views: 31000, duration: 22 },
    hashtags: ["#happyhour", "#drinks", "#oferta", "#bistrô"],
    taggedUserIds: [],
    createdAt: "2026-08-07T09:30:00Z",
    likedByMe: false,
    savedByMe: false,
  },
  {
    id: "reel-011",
    videoUrl: "https://videos.pexels.com/video-files/3195394/3195394-uhd_2560_1440_24fps.mp4",
    posterUrl: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800",
    caption: "Viagem segura e pontual. Estou disponível agora para corridas em toda a cidade!",
    category: "DRIVER" as ReelCategoryValue,
    author: {
      id: "d1",
      name: "Carlos",
      handle: "@carlos_motorista",
      photoUrl: "https://i.pravatar.cc/200?img=68",
      verified: false,
      profession: "Motorista",
      isFollowing: false,
    },
    music: {
      id: "music-011",
      title: "On the Road Again",
      artist: "Willie Nelson",
      duration: 175,
      coverUrl: null,
    },
    location: null,
    business: null,
    event: null,
    driver: {
      id: "d1",
      name: "Carlos",
      photo: "https://i.pravatar.cc/200?img=68",
      rating: 4.9,
      vehicle: "Chevrolet Onix Prata",
      plate: "ABC1D23",
      isAvailable: true,
      etaMinutes: 3,
    },
    stats: { likes: 890, comments: 45, shares: 120, saves: 78, views: 8200, duration: 22 },
    hashtags: ["#motorista", "#transporte", "#sampa", "#segurança"],
    taggedUserIds: [],
    createdAt: "2026-08-07T06:30:00Z",
    likedByMe: false,
    savedByMe: false,
  },
  {
    id: "reel-012",
    videoUrl: "https://videos.pexels.com/video-files/1485894/1485894-hd_1920_1080_24fps.mp4",
    posterUrl: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800",
    caption: "Networking descontraído: degustação de vinhos é o lugar pra conhecer gente nova!",
    category: "NETWORKING" as ReelCategoryValue,
    author: {
      id: "fernanda",
      name: "Fernanda",
      handle: "@fe.cultura",
      photoUrl: "https://i.pravatar.cc/200?img=16",
      verified: false,
      profession: "Jornalista cultural",
      isFollowing: false,
    },
    music: {
      id: "music-012",
      title: "Start Me Up",
      artist: "The Rolling Stones",
      duration: 240,
      coverUrl: null,
    },
    location: null,
    business: null,
    event: {
      id: "evt-2",
      name: "Degustação de Vinhos",
      date: "2026-08-07T19:00:00Z",
      location: "Hotel Luxe",
      coverUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800",
      interestedCount: 1240,
      attendingCount: 890,
      isInterested: false,
      isAttending: false,
      checkedIn: false,
    },
    driver: null,
    stats: { likes: 2100, comments: 95, shares: 210, saves: 180, views: 16500, duration: 30 },
    hashtags: ["#networking", "#vinhos", "#degustação", "#conexões"],
    taggedUserIds: [],
    createdAt: "2026-08-06T20:15:00Z",
    likedByMe: false,
    savedByMe: false,
  },
  {
    id: "reel-013",
    videoUrl: "https://videos.pexels.com/video-files/2325729/2325729-hd_1920_1080_30fps.mp4",
    posterUrl: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800",
    caption: "Roteiro de fim de semana: trilha de manhã e Sunset no Parque à tarde. Bora?",
    category: "TRAVEL" as ReelCategoryValue,
    author: {
      id: "pedro-henrique",
      name: "Pedro Henrique",
      handle: "@ph.dev",
      photoUrl: "https://i.pravatar.cc/200?img=5",
      verified: false,
      profession: "Dev & Trilheiro",
      isFollowing: false,
    },
    music: {
      id: "music-013",
      title: "Domingo no Parque",
      artist: "Gilberto Gil",
      duration: 260,
      coverUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=200",
    },
    location: {
      id: "sunset-parque",
      name: "Sunset no Parque",
      address: "Parque Ibirapuera — Pôr do sol com DJ set",
      lat: -23.5874,
      lng: -46.6574,
      category: "Eventos",
      distanceMeters: 2300,
    },
    business: null,
    event: null,
    driver: null,
    stats: { likes: 3900, comments: 156, shares: 340, saves: 270, views: 41000, duration: 42 },
    hashtags: ["#trilha", "#sunset", "#parqueibirapuera", "#fimdesemana"],
    taggedUserIds: ["joao-pedro"],
    createdAt: "2026-08-06T13:25:00Z",
    likedByMe: false,
    savedByMe: false,
  },
  {
    id: "reel-014",
    videoUrl: "https://videos.pexels.com/video-files/1721306/1721306-hd_1920_1080_24fps.mp4",
    posterUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
    caption: "Pocket show no parque confirmado! Guarda a vaga que o sol vai se pôr com a gente.",
    category: "MOMENT" as ReelCategoryValue,
    author: {
      id: "ana-clara",
      name: "Ana Clara",
      handle: "@ana.festa",
      photoUrl: "https://i.pravatar.cc/200?img=32",
      verified: false,
      profession: "Produtora de eventos",
      isFollowing: false,
    },
    music: {
      id: "music-014",
      title: "Garota de Ipanema",
      artist: "Tom Jobim & João Gilberto",
      duration: 200,
      coverUrl: null,
    },
    location: {
      id: "sunset-parque",
      name: "Sunset no Parque",
      address: "Parque Ibirapuera — Pôr do sol com DJ set",
      lat: -23.5874,
      lng: -46.6574,
      category: "Eventos",
      distanceMeters: 2300,
    },
    business: null,
    event: null,
    driver: null,
    stats: { likes: 1250, comments: 67, shares: 145, saves: 95, views: 11000, duration: 15 },
    hashtags: ["#momento", "#pocketshow", "#sunset", "#parque"],
    taggedUserIds: ["juliana"],
    createdAt: "2026-08-07T18:20:00Z",
    likedByMe: false,
    savedByMe: false,
  },
  {
    id: "reel-015",
    videoUrl: "https://videos.pexels.com/video-files/1721296/1721296-hd_1920_1080_24fps.mp4",
    posterUrl: "https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800",
    caption: "Bares, música e vida na Rua dos Pinheiros. A noite mal começou!",
    category: "MOMENT" as ReelCategoryValue,
    author: {
      id: "thiago",
      name: "Thiago",
      handle: "@thi.cook",
      photoUrl: "https://i.pravatar.cc/200?img=51",
      verified: false,
      profession: "Chef",
      isFollowing: true,
    },
    music: {
      id: "music-015",
      title: "Flor e o Beija-flor",
      artist: "Tim Maia",
      duration: 245,
      coverUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=200",
    },
    location: {
      id: "burger-house",
      name: "Burger House",
      address: "Rua dos Pinheiros, Pinheiros",
      lat: -23.566,
      lng: -46.6905,
      category: "Restaurantes",
      distanceMeters: 500,
    },
    business: null,
    event: null,
    driver: null,
    stats: { likes: 980, comments: 52, shares: 110, saves: 80, views: 9500, duration: 20 },
    hashtags: ["#pinheiros", "#noitesampa", "#burgerhouse", "#momento"],
    taggedUserIds: ["rafael"],
    createdAt: "2026-08-06T22:45:00Z",
    likedByMe: false,
    savedByMe: false,
  },
];
