/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as LocalizacaoRouteImport } from './routes/localizacao'
import { Route as InteressesRouteImport } from './routes/interesses'
import { Route as FinalizarPerfilRouteImport } from './routes/finalizar-perfil'
import { Route as CompletarPerfilRouteImport } from './routes/completar-perfil'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRotaRouteImport } from './routes/_app.rota'
import { Route as AppRideRouteImport } from './routes/_app/ride'
import { Route as AppReelsRouteImport } from './routes/_app.reels'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPrivacidadeRouteImport } from './routes/_app.privacidade'
import { Route as AppPessoasRouteImport } from './routes/_app.pessoas'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppNotificacoesRouteImport } from './routes/_app.notificacoes'
import { Route as AppMatchingRouteImport } from './routes/_app.matching'
import { Route as AppMarketplaceRouteImport } from './routes/_app/marketplace'
import { Route as AppLocaisRouteImport } from './routes/_app.locais'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppGerenciarRouteImport } from './routes/_app.gerenciar'
import { Route as AppFeedRouteImport } from './routes/_app/feed'
import { Route as AppEngineRouteImport } from './routes/_app/engine'
import { Route as AppDiscoverRouteImport } from './routes/_app/discover'
import { Route as AppDestinoRouteImport } from './routes/_app.destino'
import { Route as AppDesignSystemRouteImport } from './routes/_app/design-system'
import { Route as AppCreatePostRouteImport } from './routes/_app/create-post'
import { Route as AppCreateRouteImport } from './routes/_app/create'
import { Route as AppCorridaRouteImport } from './routes/_app.corrida'
import { Route as AppConnectaRouteImport } from './routes/_app.connecta'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppAvaliarRouteImport } from './routes/_app.avaliar'
import { Route as AppPerfilIndexRouteImport } from './routes/_app.perfil.index'
import { Route as AppDriverIndexRouteImport } from './routes/_app/driver/index'
import { Route as AppSolicitacaoIdRouteImport } from './routes/_app.solicitacao.$id'
import { Route as AppRideRequestRouteImport } from './routes/_app/ride/request'
import { Route as AppRideMatchingRouteImport } from './routes/_app/ride/matching'
import { Route as AppRideHistoryRouteImport } from './routes/_app/ride/history'
import { Route as AppRideActiveRouteImport } from './routes/_app/ride/active'
import { Route as AppReelsReelIdRouteImport } from './routes/_app/reels/$reelId'
import { Route as AppPerfilIdRouteImport } from './routes/_app.perfil.$id'
import { Route as AppLocalIdRouteImport } from './routes/_app.local.$id'
import { Route as AppGerenciarNovoReelRouteImport } from './routes/_app.gerenciar.novo-reel'
import { Route as AppEventEventIdRouteImport } from './routes/_app/event.$eventId'
import { Route as AppDriverProfileRouteImport } from './routes/_app/driver/profile'
import { Route as AppDriverPerformanceRouteImport } from './routes/_app/driver/performance'
import { Route as AppDriverHistoryRouteImport } from './routes/_app/driver/history'
import { Route as AppDriverFinanceRouteImport } from './routes/_app/driver/finance'
import { Route as AppDriverCadastroRouteImport } from './routes/_app/driver/cadastro'
import { Route as AppChatIdRouteImport } from './routes/_app.chat.$id'
import { Route as AppChatConversationIdRouteImport } from './routes/_app/chat.$conversationId'
import { Route as AppBusinessBusinessIdRouteImport } from './routes/_app/business.$businessId'
import { Route as AppDriverTripTripIdRouteImport } from './routes/_app/driver/trip/$tripId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalizacaoRoute = LocalizacaoRouteImport.update({
  id: '/localizacao',
  path: '/localizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const InteressesRoute = InteressesRouteImport.update({
  id: '/interesses',
  path: '/interesses',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalizarPerfilRoute = FinalizarPerfilRouteImport.update({
  id: '/finalizar-perfil',
  path: '/finalizar-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletarPerfilRoute = CompletarPerfilRouteImport.update({
  id: '/completar-perfil',
  path: '/completar-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRotaRoute = AppRotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => AppRoute,
} as any)
const AppRideRoute = AppRideRouteImport.update({
  id: '/ride',
  path: '/ride',
  getParentRoute: () => AppRoute,
} as any)
const AppReelsRoute = AppReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacidadeRoute = AppPrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => AppRoute,
} as any)
const AppPessoasRoute = AppPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchingRoute = AppMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppLocaisRoute = AppLocaisRouteImport.update({
  id: '/locais',
  path: '/locais',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppGerenciarRoute = AppGerenciarRouteImport.update({
  id: '/gerenciar',
  path: '/gerenciar',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppEngineRoute = AppEngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppDestinoRoute = AppDestinoRouteImport.update({
  id: '/destino',
  path: '/destino',
  getParentRoute: () => AppRoute,
} as any)
const AppDesignSystemRoute = AppDesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => AppRoute,
} as any)
const AppCreatePostRoute = AppCreatePostRouteImport.update({
  id: '/create-post',
  path: '/create-post',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppCorridaRoute = AppCorridaRouteImport.update({
  id: '/corrida',
  path: '/corrida',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectaRoute = AppConnectaRouteImport.update({
  id: '/connecta',
  path: '/connecta',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAvaliarRoute = AppAvaliarRouteImport.update({
  id: '/avaliar',
  path: '/avaliar',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilIndexRoute = AppPerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => AppRoute,
} as any)
const AppDriverIndexRoute = AppDriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => AppRoute,
} as any)
const AppSolicitacaoIdRoute = AppSolicitacaoIdRouteImport.update({
  id: '/solicitacao/$id',
  path: '/solicitacao/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRideRequestRoute = AppRideRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => AppRideRoute,
} as any)
const AppRideMatchingRoute = AppRideMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => AppRideRoute,
} as any)
const AppRideHistoryRoute = AppRideHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRideRoute,
} as any)
const AppRideActiveRoute = AppRideActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => AppRideRoute,
} as any)
const AppReelsReelIdRoute = AppReelsReelIdRouteImport.update({
  id: '/$reelId',
  path: '/$reelId',
  getParentRoute: () => AppReelsRoute,
} as any)
const AppPerfilIdRoute = AppPerfilIdRouteImport.update({
  id: '/perfil/$id',
  path: '/perfil/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLocalIdRoute = AppLocalIdRouteImport.update({
  id: '/local/$id',
  path: '/local/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppGerenciarNovoReelRoute = AppGerenciarNovoReelRouteImport.update({
  id: '/novo-reel',
  path: '/novo-reel',
  getParentRoute: () => AppGerenciarRoute,
} as any)
const AppEventEventIdRoute = AppEventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const AppDriverProfileRoute = AppDriverProfileRouteImport.update({
  id: '/driver/profile',
  path: '/driver/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDriverPerformanceRoute = AppDriverPerformanceRouteImport.update({
  id: '/driver/performance',
  path: '/driver/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppDriverHistoryRoute = AppDriverHistoryRouteImport.update({
  id: '/driver/history',
  path: '/driver/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDriverFinanceRoute = AppDriverFinanceRouteImport.update({
  id: '/driver/finance',
  path: '/driver/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDriverCadastroRoute = AppDriverCadastroRouteImport.update({
  id: '/driver/cadastro',
  path: '/driver/cadastro',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIdRoute = AppChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppChatRoute,
} as any)
const AppChatConversationIdRoute = AppChatConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => AppChatRoute,
} as any)
const AppBusinessBusinessIdRoute = AppBusinessBusinessIdRouteImport.update({
  id: '/business/$businessId',
  path: '/business/$businessId',
  getParentRoute: () => AppRoute,
} as any)
const AppDriverTripTripIdRoute = AppDriverTripTripIdRouteImport.update({
  id: '/driver/trip/$tripId',
  path: '/driver/trip/$tripId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/finalizar-perfil': typeof FinalizarPerfilRoute
  '/interesses': typeof InteressesRoute
  '/localizacao': typeof LocalizacaoRoute
  '/welcome': typeof WelcomeRoute
  '/avaliar': typeof AppAvaliarRoute
  '/chat': typeof AppChatRouteWithChildren
  '/connecta': typeof AppConnectaRoute
  '/corrida': typeof AppCorridaRoute
  '/create': typeof AppCreateRoute
  '/create-post': typeof AppCreatePostRoute
  '/design-system': typeof AppDesignSystemRoute
  '/destino': typeof AppDestinoRoute
  '/discover': typeof AppDiscoverRoute
  '/engine': typeof AppEngineRoute
  '/feed': typeof AppFeedRoute
  '/gerenciar': typeof AppGerenciarRouteWithChildren
  '/home': typeof AppHomeRoute
  '/locais': typeof AppLocaisRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/matching': typeof AppMatchingRoute
  '/notificacoes': typeof AppNotificacoesRoute
  '/notifications': typeof AppNotificationsRoute
  '/pessoas': typeof AppPessoasRoute
  '/privacidade': typeof AppPrivacidadeRoute
  '/profile': typeof AppProfileRoute
  '/reels': typeof AppReelsRouteWithChildren
  '/ride': typeof AppRideRouteWithChildren
  '/rota': typeof AppRotaRoute
  '/business/$businessId': typeof AppBusinessBusinessIdRoute
  '/chat/$conversationId': typeof AppChatConversationIdRoute
  '/chat/$id': typeof AppChatIdRoute
  '/driver/cadastro': typeof AppDriverCadastroRoute
  '/driver/finance': typeof AppDriverFinanceRoute
  '/driver/history': typeof AppDriverHistoryRoute
  '/driver/performance': typeof AppDriverPerformanceRoute
  '/driver/profile': typeof AppDriverProfileRoute
  '/event/$eventId': typeof AppEventEventIdRoute
  '/gerenciar/novo-reel': typeof AppGerenciarNovoReelRoute
  '/local/$id': typeof AppLocalIdRoute
  '/perfil/$id': typeof AppPerfilIdRoute
  '/reels/$reelId': typeof AppReelsReelIdRoute
  '/ride/active': typeof AppRideActiveRoute
  '/ride/history': typeof AppRideHistoryRoute
  '/ride/matching': typeof AppRideMatchingRoute
  '/ride/request': typeof AppRideRequestRoute
  '/solicitacao/$id': typeof AppSolicitacaoIdRoute
  '/driver/': typeof AppDriverIndexRoute
  '/perfil/': typeof AppPerfilIndexRoute
  '/driver/trip/$tripId': typeof AppDriverTripTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/finalizar-perfil': typeof FinalizarPerfilRoute
  '/interesses': typeof InteressesRoute
  '/localizacao': typeof LocalizacaoRoute
  '/welcome': typeof WelcomeRoute
  '/avaliar': typeof AppAvaliarRoute
  '/chat': typeof AppChatRouteWithChildren
  '/connecta': typeof AppConnectaRoute
  '/corrida': typeof AppCorridaRoute
  '/create': typeof AppCreateRoute
  '/create-post': typeof AppCreatePostRoute
  '/design-system': typeof AppDesignSystemRoute
  '/destino': typeof AppDestinoRoute
  '/discover': typeof AppDiscoverRoute
  '/engine': typeof AppEngineRoute
  '/feed': typeof AppFeedRoute
  '/gerenciar': typeof AppGerenciarRouteWithChildren
  '/home': typeof AppHomeRoute
  '/locais': typeof AppLocaisRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/matching': typeof AppMatchingRoute
  '/notificacoes': typeof AppNotificacoesRoute
  '/notifications': typeof AppNotificationsRoute
  '/pessoas': typeof AppPessoasRoute
  '/privacidade': typeof AppPrivacidadeRoute
  '/profile': typeof AppProfileRoute
  '/reels': typeof AppReelsRouteWithChildren
  '/ride': typeof AppRideRouteWithChildren
  '/rota': typeof AppRotaRoute
  '/business/$businessId': typeof AppBusinessBusinessIdRoute
  '/chat/$conversationId': typeof AppChatConversationIdRoute
  '/chat/$id': typeof AppChatIdRoute
  '/driver/cadastro': typeof AppDriverCadastroRoute
  '/driver/finance': typeof AppDriverFinanceRoute
  '/driver/history': typeof AppDriverHistoryRoute
  '/driver/performance': typeof AppDriverPerformanceRoute
  '/driver/profile': typeof AppDriverProfileRoute
  '/event/$eventId': typeof AppEventEventIdRoute
  '/gerenciar/novo-reel': typeof AppGerenciarNovoReelRoute
  '/local/$id': typeof AppLocalIdRoute
  '/perfil/$id': typeof AppPerfilIdRoute
  '/reels/$reelId': typeof AppReelsReelIdRoute
  '/ride/active': typeof AppRideActiveRoute
  '/ride/history': typeof AppRideHistoryRoute
  '/ride/matching': typeof AppRideMatchingRoute
  '/ride/request': typeof AppRideRequestRoute
  '/solicitacao/$id': typeof AppSolicitacaoIdRoute
  '/driver': typeof AppDriverIndexRoute
  '/perfil': typeof AppPerfilIndexRoute
  '/driver/trip/$tripId': typeof AppDriverTripTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/finalizar-perfil': typeof FinalizarPerfilRoute
  '/interesses': typeof InteressesRoute
  '/localizacao': typeof LocalizacaoRoute
  '/welcome': typeof WelcomeRoute
  '/_app/avaliar': typeof AppAvaliarRoute
  '/_app/chat': typeof AppChatRouteWithChildren
  '/_app/connecta': typeof AppConnectaRoute
  '/_app/corrida': typeof AppCorridaRoute
  '/_app/create': typeof AppCreateRoute
  '/_app/create-post': typeof AppCreatePostRoute
  '/_app/design-system': typeof AppDesignSystemRoute
  '/_app/destino': typeof AppDestinoRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/engine': typeof AppEngineRoute
  '/_app/feed': typeof AppFeedRoute
  '/_app/gerenciar': typeof AppGerenciarRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/locais': typeof AppLocaisRoute
  '/_app/marketplace': typeof AppMarketplaceRoute
  '/_app/matching': typeof AppMatchingRoute
  '/_app/notificacoes': typeof AppNotificacoesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/pessoas': typeof AppPessoasRoute
  '/_app/privacidade': typeof AppPrivacidadeRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reels': typeof AppReelsRouteWithChildren
  '/_app/ride': typeof AppRideRouteWithChildren
  '/_app/rota': typeof AppRotaRoute
  '/_app/business/$businessId': typeof AppBusinessBusinessIdRoute
  '/_app/chat/$conversationId': typeof AppChatConversationIdRoute
  '/_app/chat/$id': typeof AppChatIdRoute
  '/_app/driver/cadastro': typeof AppDriverCadastroRoute
  '/_app/driver/finance': typeof AppDriverFinanceRoute
  '/_app/driver/history': typeof AppDriverHistoryRoute
  '/_app/driver/performance': typeof AppDriverPerformanceRoute
  '/_app/driver/profile': typeof AppDriverProfileRoute
  '/_app/event/$eventId': typeof AppEventEventIdRoute
  '/_app/gerenciar/novo-reel': typeof AppGerenciarNovoReelRoute
  '/_app/local/$id': typeof AppLocalIdRoute
  '/_app/perfil/$id': typeof AppPerfilIdRoute
  '/_app/reels/$reelId': typeof AppReelsReelIdRoute
  '/_app/ride/active': typeof AppRideActiveRoute
  '/_app/ride/history': typeof AppRideHistoryRoute
  '/_app/ride/matching': typeof AppRideMatchingRoute
  '/_app/ride/request': typeof AppRideRequestRoute
  '/_app/solicitacao/$id': typeof AppSolicitacaoIdRoute
  '/_app/driver/': typeof AppDriverIndexRoute
  '/_app/perfil/': typeof AppPerfilIndexRoute
  '/_app/driver/trip/$tripId': typeof AppDriverTripTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cadastro'
    | '/completar-perfil'
    | '/finalizar-perfil'
    | '/interesses'
    | '/localizacao'
    | '/welcome'
    | '/avaliar'
    | '/chat'
    | '/connecta'
    | '/corrida'
    | '/create'
    | '/create-post'
    | '/design-system'
    | '/destino'
    | '/discover'
    | '/engine'
    | '/feed'
    | '/gerenciar'
    | '/home'
    | '/locais'
    | '/marketplace'
    | '/matching'
    | '/notificacoes'
    | '/notifications'
    | '/pessoas'
    | '/privacidade'
    | '/profile'
    | '/reels'
    | '/ride'
    | '/rota'
    | '/business/$businessId'
    | '/chat/$conversationId'
    | '/chat/$id'
    | '/driver/cadastro'
    | '/driver/finance'
    | '/driver/history'
    | '/driver/performance'
    | '/driver/profile'
    | '/event/$eventId'
    | '/gerenciar/novo-reel'
    | '/local/$id'
    | '/perfil/$id'
    | '/reels/$reelId'
    | '/ride/active'
    | '/ride/history'
    | '/ride/matching'
    | '/ride/request'
    | '/solicitacao/$id'
    | '/driver/'
    | '/perfil/'
    | '/driver/trip/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cadastro'
    | '/completar-perfil'
    | '/finalizar-perfil'
    | '/interesses'
    | '/localizacao'
    | '/welcome'
    | '/avaliar'
    | '/chat'
    | '/connecta'
    | '/corrida'
    | '/create'
    | '/create-post'
    | '/design-system'
    | '/destino'
    | '/discover'
    | '/engine'
    | '/feed'
    | '/gerenciar'
    | '/home'
    | '/locais'
    | '/marketplace'
    | '/matching'
    | '/notificacoes'
    | '/notifications'
    | '/pessoas'
    | '/privacidade'
    | '/profile'
    | '/reels'
    | '/ride'
    | '/rota'
    | '/business/$businessId'
    | '/chat/$conversationId'
    | '/chat/$id'
    | '/driver/cadastro'
    | '/driver/finance'
    | '/driver/history'
    | '/driver/performance'
    | '/driver/profile'
    | '/event/$eventId'
    | '/gerenciar/novo-reel'
    | '/local/$id'
    | '/perfil/$id'
    | '/reels/$reelId'
    | '/ride/active'
    | '/ride/history'
    | '/ride/matching'
    | '/ride/request'
    | '/solicitacao/$id'
    | '/driver'
    | '/perfil'
    | '/driver/trip/$tripId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/cadastro'
    | '/completar-perfil'
    | '/finalizar-perfil'
    | '/interesses'
    | '/localizacao'
    | '/welcome'
    | '/_app/avaliar'
    | '/_app/chat'
    | '/_app/connecta'
    | '/_app/corrida'
    | '/_app/create'
    | '/_app/create-post'
    | '/_app/design-system'
    | '/_app/destino'
    | '/_app/discover'
    | '/_app/engine'
    | '/_app/feed'
    | '/_app/gerenciar'
    | '/_app/home'
    | '/_app/locais'
    | '/_app/marketplace'
    | '/_app/matching'
    | '/_app/notificacoes'
    | '/_app/notifications'
    | '/_app/pessoas'
    | '/_app/privacidade'
    | '/_app/profile'
    | '/_app/reels'
    | '/_app/ride'
    | '/_app/rota'
    | '/_app/business/$businessId'
    | '/_app/chat/$conversationId'
    | '/_app/chat/$id'
    | '/_app/driver/cadastro'
    | '/_app/driver/finance'
    | '/_app/driver/history'
    | '/_app/driver/performance'
    | '/_app/driver/profile'
    | '/_app/event/$eventId'
    | '/_app/gerenciar/novo-reel'
    | '/_app/local/$id'
    | '/_app/perfil/$id'
    | '/_app/reels/$reelId'
    | '/_app/ride/active'
    | '/_app/ride/history'
    | '/_app/ride/matching'
    | '/_app/ride/request'
    | '/_app/solicitacao/$id'
    | '/_app/driver/'
    | '/_app/perfil/'
    | '/_app/driver/trip/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  CadastroRoute: typeof CadastroRoute
  CompletarPerfilRoute: typeof CompletarPerfilRoute
  FinalizarPerfilRoute: typeof FinalizarPerfilRoute
  InteressesRoute: typeof InteressesRoute
  LocalizacaoRoute: typeof LocalizacaoRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localizacao': {
      id: '/localizacao'
      path: '/localizacao'
      fullPath: '/localizacao'
      preLoaderRoute: typeof LocalizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interesses': {
      id: '/interesses'
      path: '/interesses'
      fullPath: '/interesses'
      preLoaderRoute: typeof InteressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finalizar-perfil': {
      id: '/finalizar-perfil'
      path: '/finalizar-perfil'
      fullPath: '/finalizar-perfil'
      preLoaderRoute: typeof FinalizarPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completar-perfil': {
      id: '/completar-perfil'
      path: '/completar-perfil'
      fullPath: '/completar-perfil'
      preLoaderRoute: typeof CompletarPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/rota': {
      id: '/_app/rota'
      path: '/rota'
      fullPath: '/rota'
      preLoaderRoute: typeof AppRotaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ride': {
      id: '/_app/ride'
      path: '/ride'
      fullPath: '/ride'
      preLoaderRoute: typeof AppRideRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reels': {
      id: '/_app/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AppReelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacidade': {
      id: '/_app/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof AppPrivacidadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pessoas': {
      id: '/_app/pessoas'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof AppPessoasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notificacoes': {
      id: '/_app/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matching': {
      id: '/_app/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof AppMatchingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace': {
      id: '/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locais': {
      id: '/_app/locais'
      path: '/locais'
      fullPath: '/locais'
      preLoaderRoute: typeof AppLocaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gerenciar': {
      id: '/_app/gerenciar'
      path: '/gerenciar'
      fullPath: '/gerenciar'
      preLoaderRoute: typeof AppGerenciarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/engine': {
      id: '/_app/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof AppEngineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/destino': {
      id: '/_app/destino'
      path: '/destino'
      fullPath: '/destino'
      preLoaderRoute: typeof AppDestinoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/design-system': {
      id: '/_app/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof AppDesignSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create-post': {
      id: '/_app/create-post'
      path: '/create-post'
      fullPath: '/create-post'
      preLoaderRoute: typeof AppCreatePostRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create': {
      id: '/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/corrida': {
      id: '/_app/corrida'
      path: '/corrida'
      fullPath: '/corrida'
      preLoaderRoute: typeof AppCorridaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connecta': {
      id: '/_app/connecta'
      path: '/connecta'
      fullPath: '/connecta'
      preLoaderRoute: typeof AppConnectaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/avaliar': {
      id: '/_app/avaliar'
      path: '/avaliar'
      fullPath: '/avaliar'
      preLoaderRoute: typeof AppAvaliarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil/': {
      id: '/_app/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof AppPerfilIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/driver/': {
      id: '/_app/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof AppDriverIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/solicitacao/$id': {
      id: '/_app/solicitacao/$id'
      path: '/solicitacao/$id'
      fullPath: '/solicitacao/$id'
      preLoaderRoute: typeof AppSolicitacaoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ride/request': {
      id: '/_app/ride/request'
      path: '/request'
      fullPath: '/ride/request'
      preLoaderRoute: typeof AppRideRequestRouteImport
      parentRoute: typeof AppRideRoute
    }
    '/_app/ride/matching': {
      id: '/_app/ride/matching'
      path: '/matching'
      fullPath: '/ride/matching'
      preLoaderRoute: typeof AppRideMatchingRouteImport
      parentRoute: typeof AppRideRoute
    }
    '/_app/ride/history': {
      id: '/_app/ride/history'
      path: '/history'
      fullPath: '/ride/history'
      preLoaderRoute: typeof AppRideHistoryRouteImport
      parentRoute: typeof AppRideRoute
    }
    '/_app/ride/active': {
      id: '/_app/ride/active'
      path: '/active'
      fullPath: '/ride/active'
      preLoaderRoute: typeof AppRideActiveRouteImport
      parentRoute: typeof AppRideRoute
    }
    '/_app/reels/$reelId': {
      id: '/_app/reels/$reelId'
      path: '/$reelId'
      fullPath: '/reels/$reelId'
      preLoaderRoute: typeof AppReelsReelIdRouteImport
      parentRoute: typeof AppReelsRoute
    }
    '/_app/perfil/$id': {
      id: '/_app/perfil/$id'
      path: '/perfil/$id'
      fullPath: '/perfil/$id'
      preLoaderRoute: typeof AppPerfilIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/local/$id': {
      id: '/_app/local/$id'
      path: '/local/$id'
      fullPath: '/local/$id'
      preLoaderRoute: typeof AppLocalIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gerenciar/novo-reel': {
      id: '/_app/gerenciar/novo-reel'
      path: '/novo-reel'
      fullPath: '/gerenciar/novo-reel'
      preLoaderRoute: typeof AppGerenciarNovoReelRouteImport
      parentRoute: typeof AppGerenciarRoute
    }
    '/_app/event/$eventId': {
      id: '/_app/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof AppEventEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/driver/profile': {
      id: '/_app/driver/profile'
      path: '/driver/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof AppDriverProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/driver/performance': {
      id: '/_app/driver/performance'
      path: '/driver/performance'
      fullPath: '/driver/performance'
      preLoaderRoute: typeof AppDriverPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/driver/history': {
      id: '/_app/driver/history'
      path: '/driver/history'
      fullPath: '/driver/history'
      preLoaderRoute: typeof AppDriverHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/driver/finance': {
      id: '/_app/driver/finance'
      path: '/driver/finance'
      fullPath: '/driver/finance'
      preLoaderRoute: typeof AppDriverFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/driver/cadastro': {
      id: '/_app/driver/cadastro'
      path: '/driver/cadastro'
      fullPath: '/driver/cadastro'
      preLoaderRoute: typeof AppDriverCadastroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/$id': {
      id: '/_app/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AppChatIdRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/_app/chat/$conversationId': {
      id: '/_app/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof AppChatConversationIdRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/_app/business/$businessId': {
      id: '/_app/business/$businessId'
      path: '/business/$businessId'
      fullPath: '/business/$businessId'
      preLoaderRoute: typeof AppBusinessBusinessIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/driver/trip/$tripId': {
      id: '/_app/driver/trip/$tripId'
      path: '/driver/trip/$tripId'
      fullPath: '/driver/trip/$tripId'
      preLoaderRoute: typeof AppDriverTripTripIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppChatRouteChildren {
  AppChatConversationIdRoute: typeof AppChatConversationIdRoute
  AppChatIdRoute: typeof AppChatIdRoute
}

const AppChatRouteChildren: AppChatRouteChildren = {
  AppChatConversationIdRoute: AppChatConversationIdRoute,
  AppChatIdRoute: AppChatIdRoute,
}

const AppChatRouteWithChildren =
  AppChatRoute._addFileChildren(AppChatRouteChildren)

interface AppGerenciarRouteChildren {
  AppGerenciarNovoReelRoute: typeof AppGerenciarNovoReelRoute
}

const AppGerenciarRouteChildren: AppGerenciarRouteChildren = {
  AppGerenciarNovoReelRoute: AppGerenciarNovoReelRoute,
}

const AppGerenciarRouteWithChildren = AppGerenciarRoute._addFileChildren(
  AppGerenciarRouteChildren,
)

interface AppReelsRouteChildren {
  AppReelsReelIdRoute: typeof AppReelsReelIdRoute
}

const AppReelsRouteChildren: AppReelsRouteChildren = {
  AppReelsReelIdRoute: AppReelsReelIdRoute,
}

const AppReelsRouteWithChildren = AppReelsRoute._addFileChildren(
  AppReelsRouteChildren,
)

interface AppRideRouteChildren {
  AppRideActiveRoute: typeof AppRideActiveRoute
  AppRideHistoryRoute: typeof AppRideHistoryRoute
  AppRideMatchingRoute: typeof AppRideMatchingRoute
  AppRideRequestRoute: typeof AppRideRequestRoute
}

const AppRideRouteChildren: AppRideRouteChildren = {
  AppRideActiveRoute: AppRideActiveRoute,
  AppRideHistoryRoute: AppRideHistoryRoute,
  AppRideMatchingRoute: AppRideMatchingRoute,
  AppRideRequestRoute: AppRideRequestRoute,
}

const AppRideRouteWithChildren =
  AppRideRoute._addFileChildren(AppRideRouteChildren)

interface AppRouteChildren {
  AppAvaliarRoute: typeof AppAvaliarRoute
  AppChatRoute: typeof AppChatRouteWithChildren
  AppConnectaRoute: typeof AppConnectaRoute
  AppCorridaRoute: typeof AppCorridaRoute
  AppCreateRoute: typeof AppCreateRoute
  AppCreatePostRoute: typeof AppCreatePostRoute
  AppDesignSystemRoute: typeof AppDesignSystemRoute
  AppDestinoRoute: typeof AppDestinoRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppEngineRoute: typeof AppEngineRoute
  AppFeedRoute: typeof AppFeedRoute
  AppGerenciarRoute: typeof AppGerenciarRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
  AppLocaisRoute: typeof AppLocaisRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppMatchingRoute: typeof AppMatchingRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPessoasRoute: typeof AppPessoasRoute
  AppPrivacidadeRoute: typeof AppPrivacidadeRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReelsRoute: typeof AppReelsRouteWithChildren
  AppRideRoute: typeof AppRideRouteWithChildren
  AppRotaRoute: typeof AppRotaRoute
  AppBusinessBusinessIdRoute: typeof AppBusinessBusinessIdRoute
  AppDriverCadastroRoute: typeof AppDriverCadastroRoute
  AppDriverFinanceRoute: typeof AppDriverFinanceRoute
  AppDriverHistoryRoute: typeof AppDriverHistoryRoute
  AppDriverPerformanceRoute: typeof AppDriverPerformanceRoute
  AppDriverProfileRoute: typeof AppDriverProfileRoute
  AppEventEventIdRoute: typeof AppEventEventIdRoute
  AppLocalIdRoute: typeof AppLocalIdRoute
  AppPerfilIdRoute: typeof AppPerfilIdRoute
  AppSolicitacaoIdRoute: typeof AppSolicitacaoIdRoute
  AppDriverIndexRoute: typeof AppDriverIndexRoute
  AppPerfilIndexRoute: typeof AppPerfilIndexRoute
  AppDriverTripTripIdRoute: typeof AppDriverTripTripIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAvaliarRoute: AppAvaliarRoute,
  AppChatRoute: AppChatRouteWithChildren,
  AppConnectaRoute: AppConnectaRoute,
  AppCorridaRoute: AppCorridaRoute,
  AppCreateRoute: AppCreateRoute,
  AppCreatePostRoute: AppCreatePostRoute,
  AppDesignSystemRoute: AppDesignSystemRoute,
  AppDestinoRoute: AppDestinoRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppEngineRoute: AppEngineRoute,
  AppFeedRoute: AppFeedRoute,
  AppGerenciarRoute: AppGerenciarRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
  AppLocaisRoute: AppLocaisRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppMatchingRoute: AppMatchingRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPessoasRoute: AppPessoasRoute,
  AppPrivacidadeRoute: AppPrivacidadeRoute,
  AppProfileRoute: AppProfileRoute,
  AppReelsRoute: AppReelsRouteWithChildren,
  AppRideRoute: AppRideRouteWithChildren,
  AppRotaRoute: AppRotaRoute,
  AppBusinessBusinessIdRoute: AppBusinessBusinessIdRoute,
  AppDriverCadastroRoute: AppDriverCadastroRoute,
  AppDriverFinanceRoute: AppDriverFinanceRoute,
  AppDriverHistoryRoute: AppDriverHistoryRoute,
  AppDriverPerformanceRoute: AppDriverPerformanceRoute,
  AppDriverProfileRoute: AppDriverProfileRoute,
  AppEventEventIdRoute: AppEventEventIdRoute,
  AppLocalIdRoute: AppLocalIdRoute,
  AppPerfilIdRoute: AppPerfilIdRoute,
  AppSolicitacaoIdRoute: AppSolicitacaoIdRoute,
  AppDriverIndexRoute: AppDriverIndexRoute,
  AppPerfilIndexRoute: AppPerfilIndexRoute,
  AppDriverTripTripIdRoute: AppDriverTripTripIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  CadastroRoute: CadastroRoute,
  CompletarPerfilRoute: CompletarPerfilRoute,
  FinalizarPerfilRoute: FinalizarPerfilRoute,
  InteressesRoute: InteressesRoute,
  LocalizacaoRoute: LocalizacaoRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
